엔티티 추가
E-TF/Fresh-place pull request #1
Opened 2022-04-06 05:48 UTC by suyeonkwong

## Summary
+

2022-04-06 13:56 UTC, yyy9942 requested changes
고생하셨습니다. 아래 사항에 대해 체크해보시고 코드를 수정해보시면 좋을거같아요.

1. 불필요한 Wrapper 타입을 사용하고있지는 않은지?
2. Setter가 필요한 부분에도 Setter를 안넣어서 문제가 발생하지 않을지?
3. fetchType이 LAZY가 기본값임에도 설정을 추가로 하지 않았는지?
4. EAGER가 기본값이 fetch type을 그대로 두면 문제가 발생하지 않을지?

2022-04-06 13:56 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Cart.java
> +    }
`private Long item;` 이라는부분이 이상하네요. item이라함은 객체를 뜻할거같은 네이밍입니다. 그런데 이 변수의 타입은 Long으로 이름과 타입이 매치되지 않아요. 이름을 수정하거나 타입을 수정하여 가독성있는 코드로 수정이 필요해보여요~

2022-04-06 13:56 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Code.java
> +}
이 클래스는 Setter가 없네요. Setter를 모든 컬럼에 대해 만드는건 좋지 않은 패턴이지만, 업데이트가 필요한 컬럼에는 Setter를 만들어주어야합니다.

물론 Setter 없이 불변객체로 엔티티를 관리할 수도 있지만 지금단계에서 불변객체를 다루는건 어려움이 있을듯하여 추후 불변객체에 대해 이야기해보고 적용여부를 검토해보아도 될거같아요. 지금은 필요한 컬럼에 대해 Setter를 생성해주시는게 좋을거같습니다 :)

2022-04-06 13:56 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/CodeType.java
> +}
`@ManyToOne(fetch = FetchType.LAZY)` 에 LAZY는 기본 옵션이라 지정하지 않아도 자동으로 LAZY하게 로딩합니다.
`@OneToMany`는 오히려 기본값이 EAGER라서 JPA N+1 이슈가 발생해요. LAZY옵션을 주어 불필요한 쿼리가 날아가지 않도록 세팅해주는건 어떨까요?

2022-04-06 13:56 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/DailyRanking.java
> +    @OneToOne
`@OneToOne`은 fetchType의 기본타입이 어떤것일까요?

2022-04-06 13:56 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Item.java
> +    private String category;
categoryCode로 변수명을 지어주셔도 좋을거같습니다. category라는 변수명은 뭔가 Category라는 객체를 가지고있을거같은 네이밍이네요

2022-04-06 13:56 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Member.java
> +    private String name;
이런부분들도 DB랑 이름을 맞춰주어도 좋아요. (나중에 이렇게 해야 덜헷갈립니다)
memberName 처럼요

2022-04-06 14:00 UTC, lleellee0 commented on src/main/java/individual/freshplace/entity/Member.java
> +    private String name;
테이블 이름이 이미 member 일텐데 컬럼이름마다 member가 들어갈 필요가 있을까요

2022-04-06 21:23 UTC, jinyoungchoi95 reviewed
재밌게 보고갑니다 :)

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/Cart.java
> +
```suggestion

```
불필요한 공백이 반복되네요

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/Cart.java
> +public class Cart extends BaseEntity{
전체적으로 자동으로 생성되는 기본생성자를 만들지 않고 있네요.

자동으로 생성되었을때는 물론 편리한 장점이 있지만 다른 사람과 협업한다라고 생각했을 때 기본 생성자를 명시해둘 때와 명시해두지 않을 때의 차이를 생각해보면 좋을 것 같아요. (취향차이라고 생각하긴합니다.

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/Code.java
> +
```suggestion

```
전체적으로 불필요한 공백이 군데군데 있는데 공백이 많은것 또한 가독성에 영향이 갑니다.

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/CodeType.java
> +    @OneToMany(mappedBy = "parent")
`@OneToMany`를 기본 entity 설정을 할 때부터 세팅을 한 이유가 있나요? 어디에서 사용되나요?

`@OneToMany`는 어떤 장단점이 있고 보통의 경우에 왜 지양하라는 이야기가 나올까요?

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/DailyRanking.java
> +    private LocalDateTime day;
`day`라는 필드명이 조금 안와닿지 않나요?

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/DeliverAddress.java
> +public class DeliverAddress extends BaseEntity{
```suggestion
public class DeliverAddress extends BaseEntity {
```
띄우는 것이 컨밴션입니다

2022-04-06 21:23 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/Order.java
> +    private List<OrderDetail> orderDetailList;
```suggestion
    private List<OrderDetail> orderDetails;
```
이미 타입에서 List라는게 명시되어있는데 컬랙션의 네이밍에 List를 붙이는 이유가 있나요?

2022-04-06 21:35 UTC, jinyoungchoi95 commented
> ## Summary
> @Setter를 사용함에 있어서 좋지 않은 점이 궁금합니다!

항상 코드는 모든 개발자가 같이 개발한다라는 생각으로 개발을 진행해야 해요.
혼자 개발한다면 혼자 개발하고 유지보수할테니 어떤 코드가 있던 사실 상관이 없잖아요?

그런 배경에서 `@Setter`라는 어노테이션이 열려있을 때 다른 개발자가 이걸 사용할 수 있다라는 상황을 항상 가정해야해요.
물론 더티체킹을 위해서 특정한 필드를 변경해야하는 메소드가 필요하겠죠. 그렇게 필요할 때 해당 메소드를 가령 `update~~()`로 만드는 것과 관습적인 네이밍인 setter를 모두 붙이는건 조금 다른 영역이에요. (이름에서 오는 의미 전달에서도요)

객체지향을 공부하시면 알겠지만 객체는 역할과 책임이 존재하고, 각각의 객체는 서로에게 메시지를 보내는 형태로 협력해요.
> 각각의 객체는 서로에게 메시지를 보내는 형태
가 핵심이죠. 과연 setter라는 필드를 변경하는 관습적인 메소드를 전체에다 두게되었을 때 이건 메시지를 보내는 형태일까요?

2022-04-07 07:01 UTC, suyeonkwong commented on src/main/java/individual/freshplace/entity/Address.java
> +}
이부분에 대한 접근은 생각을 못했습니다. 추가하겠습니다!

2022-04-07 07:06 UTC, suyeonkwong commented on src/main/java/individual/freshplace/entity/Address.java
> +}
> 이 클래스는 기본생성자가 있지만, 그 내부 상태인 `zipCode`, `address`에 대해서는 getter도 setter도 존재하지 않아 접근이 불가능해보여요~ 이렇게되면 이 클래스는 내부 상태가 하나도 없는 클래스와 다를게 없으니 필요한 접근메서드를 설정해주세요

2022-04-10 01:17 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Address.java
> +    }
`@AllArgsConstructor`라는 lombok을 사용하시면 직접 생성자를 작성핮 ㅣ않아도 됩니다

2022-04-10 01:22 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/DailyRanking.java
> +    private LocalDateTime date;
`dateByDay`로 맞춰주면 DB랑 이름 일치가 되어서 더 가독성이 있어질거같네요.

2022-04-13 06:53 UTC, suyeonkwong commented
> IdClass 에러는 어떻게 개선하셨나요?

@복합키 사용 시 @GeneratedValue 사용 불가능하다는 점을 알고 대체키 사용하기 위해서 식별관계를 비식별관계로 변경하였습니다. 그래서 복합키 설정인 IdClass 설정이 필요없게 되었습니다.!

2022-04-13 23:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/DeliverAddress.java
> +    private Long deliverSeq;
`deliver_add_seq` 가 DB 컬럼이고 변수명이 `deliverSeq`인듯한데요, 정상동작하나요?

2022-04-14 11:44 UTC, yyy9942 approved these changes
고생하셨습니다.
추후 작성하는 코드에서도 좋은 퀄리티를 유지해주세요 :)

2022-04-14 12:49 UTC, merged