Feature/auth
E-TF/Fresh-place pull request #2
Opened 2022-04-29 11:29 UTC by suyeonkwong

2022-04-29 12:09 UTC, yyy9942 commented
나머지 내용은 PR에 대한 내용을 정리해주시면 리뷰진행하겠습니다

2022-05-04 07:51 UTC, suyeonkwong commented
ㅇㄹ

2022-05-05 02:05 UTC, yyy9942 commented
Readme.md 파일은 프로젝트 전역적으로 설명하는 내용을 추가하는겁니다. PR과 관련된 내용은 이 Pull Request 내부에 적어주세요
![image](https://user-images.githubusercontent.com/46917538/166854148-b348eee9-2c13-47c0-b06b-39abed098fac.png)

2022-05-11 03:09 UTC, suyeonkwong commented
> 굳이 숫자로 미리 바꿔두실 필요는 없을거같네요. Duration type으로 둬도 될거같습니다. 숫자로 써야할 때 숫자로 변환하면 되니까요

Duration type으로 변경하겠습니다!

2022-05-12 13:42 UTC, suyeonkwong commented
> @suyeonkwong 계속 커밋중인듯한데요, 완료되시면 코멘트로 저 소환해주세요 ㅎㅎ

@yyy9942 넹 ㅎㅎ

2022-05-12 13:43 UTC, suyeonkwong commented
> @suyeonkwong 계속 커밋중인듯한데요, 완료되시면 코멘트로 저 소환해주세요 ㅎㅎ

@yyy9942 완료되었습니다!

2022-05-14 14:35 UTC, yyy9942 requested changes

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/JwtProperties.java
> +    public static final Duration EXPIRATION_TIME_TO_HOURS = Duration.ofHours(1);
Duratrion Type이기 때문에 `EXPIRATION_TIME_TO_HOURS `처럼 뒤에 HOURS를 붙이지 않아도 됩니다. `EXPIRATION_TIME`정도가 적절한 네이밍으로 보이네요

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +    }
```
catch (IOException e) {
            e.printStackTrace();
        }
```
별도 Exception 발생 없이 로그만 찍고 넘어가도 괜찮을까요?

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +        String memberId = validateToken(request, changeToken);
`validateToken` 이라는 이름의 메서드라면 토큰에 대해 검증하는 역할을 수행할 것으로 기대할 수 있습니다.
하지만 실제 메서드의 수행 내용은 검증이라기보다는 토큰을 복호화하여 id를 조회하는 용도로 쓰이고 있는 것으로 보여요. 검증하는 용도의 메서드라면 검증하는 내용만 들어있어야 하며, 복호화를 하려한다면 복호화의 내용으로 메서드 네임을 지어주세요.

협업 진행시 변수의 이름, 메서드의 이름을 명확하게 지어야 네이밍 오류로 인한 버그와 오류를 사전에 방지할 수 있으며 코드 가독성또한 늘어날 수 있어요. `validateToken`메서드를 호출했는데 String Type의 리턴값이 온다면 이게 어떤 반환값인지 예측하기 힘들겠죠?

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +    }
return값을 null로 준 후 이 리턴값에 대한 에러처리를 메서드 밖에서하는건 상당히 위험한 예외처리 접근법이에요. Request에 토큰값이 없다면 명시적으로 Exception을 던져주는것이 좋을 것 같습니다. null을 이용한 예외처리는 지양해주세요.

이렇게 예외처리를 할 경우 문제가 되는 부분은
1. 이 코드를 개발한 개발자가 아니면 어떻게 리턴값이 오고 어떻게 예외처리를 해야하는지 예측하기 어려우며
2. 예외처리를 하지 않고 넘어간다면 이 null값으로 인해 엉뚱한곳에서 예측하지 못한 오류가 발생할 수 있고
3. 예외에 대한 추적이 어려워집니다.

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +        Member member = memberRepository.findByMemberId(memberId).get();
만약 memberId로 조회했는데 멤버가 없다면 `.get();`으로 인해 예외가 발생할 것입니다.
null이 올 수도 있기 때문에 orElseThrow로 명시적인 예외처리를 해주세요

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +            request.setAttribute(JwtProperties.EXCEPTION, e.getClass().getSimpleName());
이 경우에는 사실상 예외처리를 해야할 것으로 보이네요

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        }
회원가입 신청이 들어왔는데 어떤 예외가 와도 '회원가입실패'라는 메세지가 오면 어떤게 문제인지 알기 어려울 것이에요. 그리고 이런식으로 단순히 Return해주면 HTTP Status는 200 OK로 내려가기 때문에 에러인지 알기 어려울 가능성도 높습니다. (메세지를 이용해서 에러인지 판단하는건 하드코딩이 들어가야 하기 때문에 지양해야 합니다.)

에러인지 성공인지는 HTTP 상태코드를 통해 지정해주세요. 서버쪽 에러면 500대, 클라이언트의 입력값 오류면 400대 오류를 내려주시면 됩니다. 어떤 에러 코드가 있는지는 [여기](https://ko.wikipedia.org/wiki/HTTP_%EC%83%81%ED%83%9C_%EC%BD%94%EB%93%9C)를 참고해주세요.

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        }
상태에 따라 HTTP Status 값을 다르게 내려주고 싶다면 ResponseEntity를 리턴해보는것도 좋은 시도가 될겁니다.

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/LoginDto.java
> +@Data
`@Data`를 꼭 써야할까요?
Lombok에서 `@Data`는 너무나 많은 역할을 해주기 때문에, 어떤 작업까지 되는지 예측하기 어려운 경우도 있습니다.
꼭 필요한 Lombok 어노테이션만 명시적으로 지정해주세요.

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/SignUpDto.java
> +    private String phNum;
String에 NotEmpty 밸리데이션을 붙이게 된다면 null, "" 값은 막을 수 있겠지만 " " 값은 막을 수 없을 것입니다.
NotBlank를 사용해보세요.

또한 이 값들을 누락했을 때 에러메세지도 직접 지정이 가능합니다.

phNum과 같이 줄임말을 쓰는건 조심해서 사용해주세요. 정말 누구나 알고있는 줄임말이 아니라면 풀어서 쓰는것이 좋습니다. 나중에 이게 무엇을 뜻하는건지 찾기 어렵거든요.

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        }
memberRepository.findByMemberId(signUpDto.getMemberId()).orElseThrow(() -> new RuntimeException("이미 가입된 회원입니다.")) 와 동일한 코드가 될거같네요

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        DiscountByGrade grade = discountByGradeRepository.getById("01");
"01" 과 같은 값은 어떤 의미를 가지고있는지도 알기 어렵고 코드에 박힌 알 수 없는 상수입니다. 이런 값을 보통 하드코딩이라고 부르는데 레거시 코드를 만드는 주범이기도 해요.

이런 값은 상수를 만들어 이름을 지어주어야 어떤 값인지 알 수 있습니다.
```
discountByGradeRepository.getById("01");
discountByGradeRepository.getById(CODE_GRADE_XXX);
```

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        DiscountByGrade grade = discountByGradeRepository.getById("01");
getById 가 아닌 findById가 요즘 JPA 컨벤션으로 변경되었고, 이미 findById라는게 있을거에요~

2022-05-14 14:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +
공백 제거해주세요~

2022-05-14 14:54 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/JwtProperties.java
> +    }
> secret의 경우 한번 설정되면 변경을 하지 않을것으로 보이는데요, 불변 변수인 final로 선언하는것이 좋아보입니다.

네 final로 선언하겠습니다.

2022-05-15 11:27 UTC, jinyoungchoi95 reviewed
재밌게 보고 갑니당 🚀

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +        }
```suggestion
        } catch (NoSuchElementException e) {
            log.info("토큰 검증에 실패하였습니다.");
        } finally {
            chain.doFilter(request, response);
        }
```
👀

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    @PostMapping("/public/signup")
현재 컨트롤러는 Member를 관리하게 되는데요. url에 `members`가 아닌 `public`이 들어간 이유가 있을까요?

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    public String join(@Valid @RequestBody SignUpDto signUpDto) {
`SignUpDto`는 너무 포괄적인 것 같아요.
저희가 사용하게될 Dto는 요청인 `request`, 반환인 `response`가 생기게 될건데요. 이를 구분하지 않은 이유가 있을까요?

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/Member.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
방어적 코딩 👍

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/repository/MemberRepository.java
> +import java.util.Optional;
```suggestion
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.Optional;
```
👀

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +                .build();
결국 모든 값은 `Dto`를 통해서 `Entity`로 변환되고 있는데요. Service에서 변환을 하는것이아닌 필드를 가지고 있는 객체에서 변환하는 방법도 고려할 수 있지 않을까요? (취향차이일뿐 정답은 없다라고 생각하셔도됩니당)

2022-05-15 11:27 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/repository/DiscountByGradeRepository.java
> +public interface DiscountByGradeRepository extends JpaRepository<DiscountByGrade, String> {
Pk가 String이 된 이유가 궁금하네요 :)

2022-05-20 07:56 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    public String join(@Valid @RequestBody SignUpDto signUpDto) {
> `SignUpDto`는 너무 포괄적인 것 같아요. 저희가 사용하게될 Dto는 요청인 `request`, 반환인 `response`가 생기게 될건데요. 이를 구분하지 않은 이유가 있을까요?

dto 네이밍에 대해 생각해보지 않았는데 request와 response를 구문하는게 좋을것같으므로 구분하도록 하겠습니다.

2022-05-20 09:07 UTC, suyeonkwong commented on src/main/java/individual/freshplace/repository/DiscountByGradeRepository.java
> +public interface DiscountByGradeRepository extends JpaRepository<DiscountByGrade, String> {
> Pk가 String이 된 이유가 궁금하네요 :)

Pk가 '이름+01',02,03이런식이어서 String이 되었습니다.

2022-05-20 09:11 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    @PostMapping("/public/signup")
> 현재 컨트롤러는 Member를 관리하게 되는데요. url에 `members`가 아닌 `public`이 들어간 이유가 있을까요?

/public/** 이렇게 들어가는 부분은 권한처리를 하지 않기 위해서입니다.

2022-05-20 09:13 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +
> 불필요한 공백 👀

엇 주의 하도록 하겠습니다! 👀

2022-05-20 09:25 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationEntryPoint.java
> +}
> `EOL` 키워드 한번확인해보시고 고쳐보세용~

혹시 L이 Line일까요?

2022-05-20 10:04 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +
> 공백 제거해주세요~

넵 :smile:

2022-05-20 10:13 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +        DiscountByGrade grade = discountByGradeRepository.getById("01");
> getById 가 아닌 findById가 요즘 JPA 컨벤션으로 변경되었고, 이미 findById라는게 있을거에요~

네 findById로 변경하겠습니다~

2022-05-20 10:15 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +        DiscountByGrade grade = discountByGradeRepository.getById("01");
> "01" 과 같은 값은 어떤 의미를 가지고있는지도 알기 어렵고 코드에 박힌 알 수 없는 상수입니다. 이런 값을 보통 하드코딩이라고 부르는데 레거시 코드를 만드는 주범이기도 해요.
> 
> 이런 값은 상수를 만들어 이름을 지어주어야 어떤 값인지 알 수 있습니다.
> 
> ```
> discountByGradeRepository.getById("01");
> discountByGradeRepository.getById(CODE_GRADE_XXX);
> ```

네 상수로 이름을 지정하겠습니다!!

2022-05-20 10:22 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +        }
> memberRepository.findByMemberId(signUpDto.getMemberId()).orElseThrow(() -> new RuntimeException("이미 가입된 회원입니다.")) 와 동일한 코드가 될거같네요

이미 회원이 있을 경우 (null이 아닐 경우) 에 throw하는 경우라서 null일 경우 예외를 던지면 Duplication검사가 힘들것같습니다!

2022-05-20 10:25 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/SignUpDto.java
> +    private String phNum;
> String에 NotEmpty 밸리데이션을 붙이게 된다면 null, "" 값은 막을 수 있겠지만 " " 값은 막을 수 없을 것입니다. NotBlank를 사용해보세요.
> 
> 또한 이 값들을 누락했을 때 에러메세지도 직접 지정이 가능합니다.
> 
> phNum과 같이 줄임말을 쓰는건 조심해서 사용해주세요. 정말 누구나 알고있는 줄임말이 아니라면 풀어서 쓰는것이 좋습니다. 나중에 이게 무엇을 뜻하는건지 찾기 어렵거든요.

네 member의 핸드폰 번호를 뜻하는데 phone_number로 변경하겠습니다.

2022-05-20 10:39 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/LoginDto.java
> +@Data
> 

네 필요한 어노테이션만 지정하겠습니다:simple_smile:

2022-05-20 10:39 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/LoginDto.java
> +@Data
> `@Data`를 꼭 써야할까요? Lombok에서 `@Data`는 너무나 많은 역할을 해주기 때문에, 어떤 작업까지 되는지 예측하기 어려운 경우도 있습니다. 꼭 필요한 Lombok 어노테이션만 명시적으로 지정해주세요.

네 필요한 :simple_smile:

2022-05-20 13:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/auth/PrincipalDetailsService.java
> +        Member member = memberEntity.orElseThrow(() -> new UsernameNotFoundException("사용자를 찾을 수 없습니다."));
제가 드린 리뷰는, new 키워드로 굳이 예외객체를 만들어 던져야는거에요. static한 예외라면 static 변수로 만들어두고 쓴다면 매번 새로운 객체를 안만들어도 될 것 같습니다.

2022-05-20 14:20 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +        config.addAllowedMethod(String.valueOf(Arrays.asList(HttpMethod.GET, HttpMethod.POST)));
> PUT, PATCH는 사용하지 않을 것인가요? 또한 CORS preflight때문이라도 OPTION 메서드는 허용해주어야할거같네요. preflight에 대해서도 알아보면 좋을거같습니다 :)

CORS 는 먼저 OPTIONS 요청을 보내서 서버에서 어떤 method나 header를 허용하는지 확인하고 해당 정보를 토대로 통신의 가능 여부를 파악하는 과정을 preflight라고 합니다! 수정을 담당하는 PUT과 PATCH도 추가하겠습니다.

2022-05-20 14:23 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationEntryPoint.java
> +        }
> 사용자에게 실제로 내려가는 에러 값일텐데요, Exception 내용에 대해 좀더 깔끔하게 정리해주어도 좋을거같습니다. request에서 exception이라는 값을 꺼내면 어떤 값이 내려갈까요?

인증 필터에서 생긴 exception내용별로 JSONObject를 사용해서 response하는게 좋을것같습니다.

2022-05-20 14:28 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +    }
> HttpServletRequest의 Input Stream은 1회용입니다. 한번 읽으면 이후에 다시 스트림을 읽어들일 수 없기 때문에 필터에서 읽게되면 이후에 파라미터가 유실될 수 있어요.
> 
> 단순히 파라미터를 읽으려는 것이라면 [이 글](https://hihoyeho.tistory.com/entry/getInputSream-%EB%B0%8F-getReader-%EC%82%AC%EC%9A%A9-%ED%9B%84-parameter-%EC%86%90%EC%8B%A4)을 참조하여 스트림을 소모하지 않도록 유의해주세요

HttpServletRequest의 Input Stream이 일회용이라 필터에서 값을 소모하게 되면 컨트롤러에서 나중에 값을 처리 할 수 없게 됩니다. 그래서 HttpServletRequestWrapper 클래스를 만들어서 다시 데이터를 생성하도록 하는 방법을 사용해보겠습니다

2022-05-20 14:30 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +        String memberId = validateToken(request, changeToken);
> `validateToken` 이라는 이름의 메서드라면 토큰에 대해 검증하는 역할을 수행할 것으로 기대할 수 있습니다. 하지만 실제 메서드의 수행 내용은 검증이라기보다는 토큰을 복호화하여 id를 조회하는 용도로 쓰이고 있는 것으로 보여요. 검증하는 용도의 메서드라면 검증하는 내용만 들어있어야 하며, 복호화를 하려한다면 복호화의 내용으로 메서드 네임을 지어주세요.
> 
> 협업 진행시 변수의 이름, 메서드의 이름을 명확하게 지어야 네이밍 오류로 인한 버그와 오류를 사전에 방지할 수 있으며 코드 가독성또한 늘어날 수 있어요. `validateToken`메서드를 호출했는데 String Type의 리턴값이 온다면 이게 어떤 반환값인지 예측하기 힘들겠죠?

메서드 이름을 validateToken에서 decryptToken으로 변경하겠습니다.

2022-05-20 14:34 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +    }
> return값을 null로 준 후 이 리턴값에 대한 에러처리를 메서드 밖에서하는건 상당히 위험한 예외처리 접근법이에요. Request에 토큰값이 없다면 명시적으로 Exception을 던져주는것이 좋을 것 같습니다. null을 이용한 예외처리는 지양해주세요.
> 
> 이렇게 예외처리를 할 경우 문제가 되는 부분은
> 
> 1. 이 코드를 개발한 개발자가 아니면 어떻게 리턴값이 오고 어떻게 예외처리를 해야하는지 예측하기 어려우며
> 2. 예외처리를 하지 않고 넘어간다면 이 null값으로 인해 엉뚱한곳에서 예측하지 못한 오류가 발생할 수 있고
> 3. 예외에 대한 추적이 어려워집니다.

null을 리턴하지 않고 그대로 변경하지 않은 tokenValue를 리턴해서 인증 실패시 AuthenticationEntryPoint로 이동하는 방법이 좋을것같습니다!

2022-05-20 14:35 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +        Member member = memberRepository.findByMemberId(memberId).get();
> 만약 memberId로 조회했는데 멤버가 없다면 `.get();`으로 인해 예외가 발생할 것입니다. null이 올 수도 있기 때문에 orElseThrow로 명시적인 예외처리를 해주세요

네! orElseThrow로 던져서 잡아주겠습니다

2022-05-20 14:38 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        }
> 회원가입 신청이 들어왔는데 어떤 예외가 와도 '회원가입실패'라는 메세지가 오면 어떤게 문제인지 알기 어려울 것이에요. 그리고 이런식으로 단순히 Return해주면 HTTP Status는 200 OK로 내려가기 때문에 에러인지 알기 어려울 가능성도 높습니다. (메세지를 이용해서 에러인지 판단하는건 하드코딩이 들어가야 하기 때문에 지양해야 합니다.)
> 
> 에러인지 성공인지는 HTTP 상태코드를 통해 지정해주세요. 서버쪽 에러면 500대, 클라이언트의 입력값 오류면 400대 오류를 내려주시면 됩니다. 어떤 에러 코드가 있는지는 [여기](https://ko.wikipedia.org/wiki/HTTP_%EC%83%81%ED%83%9C_%EC%BD%94%EB%93%9C)를 참고해주세요.

실패시 BadRequest를 내려주는것이 좋을 것 같아서 회원가입로직에서 예외가 생기면 400이 내려가게 하도록 하겠습니다.

2022-05-20 15:44 UTC, kwj1270 reviewed
안녕하세요 저도 지나가다가 들립니다.  
코드 작성하신 내용 하나 하나 읽어보니 신경 쓰시는게 보이는 것 같네요 👍 
소소한 피드백 남겼으니, 동의하신다면 반영해주시고 아니라면 참고로만 생각해주세요 :)

2022-05-20 15:44 UTC, kwj1270 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        if (memberRepository.findByMemberId(signupRequest.getMemberId()).orElse(null) != null) {
Optional 을 이용해서 처리하려는 의도는 좋습니다 👍 
다만, findBy 말고도 exist 문법이 존재하는 걸로 알고 있는데 이를 활용하면 간략해질 것 같아요

2022-05-20 15:44 UTC, kwj1270 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +        UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(loginRequest.getMemberId(),loginRequest.getPassword());
```suggestion
        UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(loginRequest.getMemberId(), loginRequest.getPassword());
```

2022-05-20 15:44 UTC, kwj1270 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +    }
우선 의도가 무엇인지 잘 모르고 리뷰드리는 점 양해 부탁드려요 

코드를 확인했을 때, 
만약 에러가 발생하면 null 값을 `getLoginAuthentication`에 넘겨주는 것으로 보이고   
`getLoginAuthentication()` 코드는 null 에 대한 처리가 나지 않아서 NPE가 발생할 가능성이 커 보이는 것 같아요

2022-05-21 05:05 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +        if (memberRepository.findByMemberId(signupRequest.getMemberId()).orElse(null) != null) {
> Optional 을 이용해서 처리하려는 의도는 좋습니다 👍 다만, findBy 말고도 exist 문법이 존재하는 걸로 알고 있는데 이를 활용하면 간략해질 것 같아요

덕분에 existsByMemberId 사용해서 코드가 더 간결해졌습니다!! 😃😄 감사해요

2022-05-21 05:06 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +}
> `@Slf4j` 를 선언하셨지만, 사용하지 않는 것으로 보여지네요 :)

엇 주의 하도록 하겠습니다 !!

2022-05-21 05:06 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +        UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(loginRequest.getMemberId(),loginRequest.getPassword());
> 

띄어쓰기.... 꼼꼼하게 봐주셔서 감사합니다..

2022-05-21 05:33 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationFilter.java
> +    }
> 우선 의도가 무엇인지 잘 모르고 리뷰드리는 점 양해 부탁드려요
> 
> 코드를 확인했을 때, 만약 에러가 발생하면 null 값을 `getLoginAuthentication`에 넘겨주는 것으로 보이고 `getLoginAuthentication()` 코드는 null 에 대한 처리가 나지 않아서 NPE가 발생할 가능성이 커 보이는 것 같아요

만약 getLoginAuthentication() 에서 예외가 날 경우 unsuccessfulAuthentication() 가 실행되므로 
로그인 실패 response가 내려지게 됩니다!

2022-05-21 05:40 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/auth/PrincipalDetailsService.java
> +        Member member = memberEntity.orElseThrow(() -> new UsernameNotFoundException("사용자를 찾을 수 없습니다."));
> 제가 드린 리뷰는, new 키워드로 굳이 예외객체를 만들어 던져야는거에요. static한 예외라면 static 변수로 만들어두고 쓴다면 매번 새로운 객체를 안만들어도 될 것 같습니다.

네! static하게 변경하겠습니다

2022-05-21 08:06 UTC, yyy9942 requested changes
확인한건 resolve처리 해두었어요~ resolve되지 않은건 확인부탁드려요

2022-05-21 12:47 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +    }
> SecurityConfig 클래스에서 `@Value("${cors.alloworigin}") String localOrigin` 를 주입받아도 될 것 같은데요, 별도 Origin 클래스를 생성하여 빈으로 등록한 이유가 있으신가요? 불필요한 빈이라는 생각이 들어서요

제가 처음에 SecurityConfig 에서 String타입으로 localOrigin을 똑같이 @Value를 사용해서 값을 가져오려고 했는데 @RequiredArgsConstructor 이 어노테이션 때문에 final이 붙은 필드들이 다 생성자로 만들어져서 계속 에러가 났습니다. 그래서 지금처럼 따로 빈으로 등록해서 사용했었는데 final을 뺏더니 SecurityConfig에서 @Value를 사용해도 잘 들어와요! 수정헤서 커밋하도록 하겠습니다.

2022-05-21 13:00 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.BAD_CODE, GradeCode.CODE_GRADE_GENERAL));
> `new WrongValueException(ErrorCode.BAD_CODE, GradeCode.CODE_GRADE_GENERAL)` 도 예외 객체를 생성하는건데요, 변하지 않는 상수 객체로 보입니다. static하게 관리해서 불필요하게 객체생성을 하지 않도록 해주세요

네!!

2022-05-21 13:16 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationEntryPoint.java
> +            responseError(response, ErrorCode.NON_HEADER_AUTHORIZATION);
> else if 문은 가독성이 떨어지고, 조건문에 대한 추적이 어려워질 수 있기 때문에 사용하지 않는편이 좋습니다. if문만으로도 동일한 효과를 낼 수 있어요.
> 
> ```
>  if (error.equals(ErrorCode.EXPIRED_TOKEN.name())) {
>             responseError(response, ErrorCode.EXPIRED_TOKEN);
> }
> if (error.equals(ErrorCode.INVALID_TOKEN.name())) {
>             responseError(response, ErrorCode.INVALID_TOKEN);
>  }
> if (error.equals(ErrorCode.NON_HEADER_AUTHORIZATION.name())) {
>             responseError(response, ErrorCode.NON_HEADER_AUTHORIZATION);
> }
> ```


> null safe한 코드를 만들려면 이렇게 바꾸는게 좋아요. (error가 null이 되면 NPE가 발생하겠죠?)
> 
> ```
>  if (ErrorCode.EXPIRED_TOKEN.name().equals(error)) {
>             responseError(response, ErrorCode.EXPIRED_TOKEN);
> }
> ```

네 ~~ !!

2022-05-24 23:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthenticationEntryPoint.java
> +}
End Of Line입니다~

2022-05-24 23:59 UTC, jinyoungchoi95 reviewed
🚀

2022-05-24 23:59 UTC, jinyoungchoi95 commented on build.gradle
> +	implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
스프링에서 Jackson을 제공하는데 해당 라이브러리를 추가한 이유가 있을까요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/config/JwtProperties.java
> +    public static final String EXCEPTION = "exception";
상수는 클래스 변수 위로 올리는 것이 컨벤션입니다~

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/config/auth/PrincipalDetailsService.java
> +        Member memberEntity = memberRepository.findByMemberId(memberId).orElseThrow(() -> exception);
```suggestion
        Member memberEntity = memberRepository.findByMemberId(memberId)
            .orElseThrow(() -> new UsernameNotFoundException("사용자를 찾을 수 없습니다."));
```
제생각에는 굳이 exception을 상수로 뺄 필요는 없어보여요.
그렇다고 상수의 네이밍이 exception으로 큰 의미를 가지고 있지도 않구요. 어떻게 생각하세요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/config/auth/PrincipalDetailsService.java
> +    private static UsernameNotFoundException exception = new UsernameNotFoundException("사용자를 찾을 수 없습니다.");
```suggestion
    private final static UsernameNotFoundException exception = new UsernameNotFoundException("사용자를 찾을 수 없습니다.");
```
만약 상수로 쓴다면 `접근제어자 final static`은 붙여서 사용해주세요~

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +public class JwtAuthorizationFilter extends BasicAuthenticationFilter {
`BasicAuthenticationFilter`가 뭔지 설명한번만 부탁드려요 :)

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    @PostMapping("/public/signup")
그럼 현재는 members를 관리하고 있으니 `/public/members/signup`이 더 맞지 않을까요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/dto/SignupRequest.java
> +public class SignupRequest {
`@Setter`의 사용이 꼭 필요한가요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +public class MemberService {
지금까지 코드를 봤을 때 어노테이션의 배치 순서가 고려되지 않은 것 같은데요.
혼자만의 프로젝트이더라도 어떻게 코드를 배치해야하는지 컨벤션을 고려하고 표현하는걸 연습하시면 좋을 것 같네요 :)

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +    private final BCryptPasswordEncoder bCryptPasswordEncoder;
```suggestion
    private final PasswordEncoder PasswordEncoder;
```
구현체에 의존하지 않아도된다고 생각하는데 어떻게 생각하세요?
그리고 제가 말씀드리는 구현체에 의존하지 않아야된다라는 이야기는 왜 나온것이며 무슨 장점이 있을까요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        }
"이미 존재하는 아이디를 반환한다"라는 메소드로 분리해서 사용하면 어떨까요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        Member member = Member.builder()
저번에도 말씀을 드렸던 부분이지만 request의 요구사항이 변경되었을 때 여기 있는 Member로 변환하는 Service의 코드도 함께 변경되어야해요.
controller에서의 변경점의 여파가 service까지 내려오는데 이렇게 진행하면 무슨 단점이 있을까요?

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/util/ErrorCode.java
> +public enum ErrorCode {
에러코드 관리 객체 👍

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/util/ErrorResponse.java
> +@Builder
자기자신만 쓰는 용도로 만드는 `@Builder`는 과연 효용성이 있을까라는 생각이 드네요 🤔

2022-05-24 23:59 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
코드 실행중에 발생하는 다른 Exception은 여기서 관리되고 있지 않는걸로 보이네요

2022-05-25 10:35 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
> 코드 실행중에 발생하는 다른 Exception은 여기서 관리되고 있지 않는걸로 보이네요

일단 @ControllerAdvice에서는 filter의 예외를 잡아주지 못하므로 filter단에서 발생하는 예외는 이곳에서 처리하지 않았습니다 !!

2022-05-25 11:53 UTC, suyeonkwong commented on build.gradle
> +	implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
> 스프링에서 Jackson을 제공하는데 해당 라이브러리를 추가한 이유가 있을까요?

LocalDateTime항목을 가져올 경우 직렬화 또는 역직렬화 하기 위해 jackson-datetype 라이브러리를 추가해주어야 하기 때문입니다.

2022-05-25 11:57 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/JwtProperties.java
> +    public static final String EXCEPTION = "exception";
> 상수는 클래스 변수 위로 올리는 것이 컨벤션입니다~

네~

2022-05-25 12:02 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/auth/PrincipalDetailsService.java
> +        Member memberEntity = memberRepository.findByMemberId(memberId).orElseThrow(() -> exception);
> 제생각에는 굳이 exception을 상수로 뺄 필요는 없어보여요. 그렇다고 상수의 네이밍이 exception으로 큰 의미를 가지고 있지도 않구요. 어떻게 생각하세요?

일단 변수명은 의미를 가지도록 usernameNotFoundException로 변경하는게 좋을것같습니다. !!

2022-05-25 12:09 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/jwt/JwtAuthorizationFilter.java
> +public class JwtAuthorizationFilter extends BasicAuthenticationFilter {
> `BasicAuthenticationFilter`가 뭔지 설명한번만 부탁드려요 :)

BasicAuthenticationFilter는 요청 헤더의 값을 읽어와 SecurityContextHolder에 저장하며 매번 요청마다 인증을 시도하므로 stateless하다는 특징이 있습니다! ㅎㅎ

2022-05-25 12:56 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +    private final BCryptPasswordEncoder bCryptPasswordEncoder;
> 구현체에 의존하지 않아도된다고 생각하는데 어떻게 생각하세요? 그리고 제가 말씀드리는 구현체에 의존하지 않아야된다라는 이야기는 왜 나온것이며 무슨 장점이 있을까요?

구현체에 의존할 경우 구체화에 의존하지 않고 추상화에 의존해야 한다는 DIP원칙에 위반됩니다. 스프링에서는 DI컨테이너를 통해  의존관계를 주입할 수 있으므로 구현체를 변경하고싶다면 외부에서 구현체를 주입하고 내부에서는 추상화를 의존하여 내부코드의 변경없이 확장이 가능한 객체지향설계원칙을 지킬 수 있다는 장점이 있습니다. 해당 코드는 변경하도록 하겠습니다.

2022-05-25 15:26 UTC, yyy9942 approved these changes
고생하셨습니다. 이번 PR로 얻은 Spring Security 및 보안/인증/인가와 관련된 지식은 잊지 말고 체득하여 가지고 갈 수 있도록 해주세요. 추가로 코드관련 리팩토링이나 수정할 부분 있으면 수정하신 후 머지해주시면 될 것으로 보입니다.

ReadMe.md파일에서 conflict가 나는것으로 보이는데 이것도 해결해보시면 좋을듯하네요 :)

2022-05-26 03:20 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +        Member member = Member.builder()
> 저번에도 말씀을 드렸던 부분이지만 request의 요구사항이 변경되었을 때 여기 있는 Member로 변환하는 Service의 코드도 함께 변경되어야해요. controller에서의 변경점의 여파가 service까지 내려오는데 이렇게 진행하면 무슨 단점이 있을까요?

피드백을 확인하고 dto의 사용범위에 대해 찾아봤습니다.  우선 service에서 controller의 dto를 그대로 받아서 사용할 경우  service에서 원하는 포맷으로 데이터를 받을 수 없다는 점과 해당 service를 여러 controller에서 사용하지 못한다는 단점이 있습니다. 일단 서비스에서 dto를 원하는 포맷으로 받을수 있도록 하는 방법을 고려해보도록 하겠습니다.

2022-05-30 09:22 UTC, merged