축소파일을 비동기로 업로드하기
E-TF/Fresh-place pull request #25
Opened 2022-11-20 06:00 UTC by suyeonkwong

가로크기가 2000px이상인 파일사이즈를 축소할 경우 응답시간이 4초가 걸리므로 빠른 응답을 위해 원본저장이 성공하면
response처리하고 이미지 리사이즈 과정을 비동기로 처리하도록 했습니다. image entity 구조도 변경했습니다!

2022-11-20 07:36 UTC, yyy9942 requested changes

2022-11-20 07:36 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/FImageUploadService.java
> +    }
리사이징이 실패하는 경우를 고려한다면 어떻게 failover처리를 할 수 있을까요?

2022-11-25 10:17 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/FImageUploadService.java
> +    }
> 리사이징이 실패하는 경우를 고려한다면 어떻게 failover처리를 할 수 있을까요?

실패할 경우 관리자에게 메일로 실패를 알리는 방법으로 failover를 처리 할 수 있습니다!

2022-11-26 13:30 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +    private final static String RECEIVER =  "rnjstndus23@gmail.com";
요런 이메일주소는 profile별로 달라질 수 있기때문에 application.yaml등에서 설정으로 관리해주시는게 좋습니다.

2022-11-26 13:46 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +    private final static String RECEIVER =  "rnjstndus23@gmail.com";
> 요런 이메일주소는 profile별로 달라질 수 있기때문에 application.yaml등에서 설정으로 관리해주시는게 좋습니다.

넵

2022-11-27 03:14 UTC, yyy9942 approved these changes
머지하셔도 좋습니다~

2022-11-27 04:33 UTC, merged