프로필 관리
E-TF/Fresh-place pull request #3
Opened 2022-06-04 09:34 UTC by suyeonkwong

회원가입과 프로필 수정에 대한 기능입니다. 
로그인 인증 객체를 가져오기 위해 @AuthenticationPrincipal 를 사용했는데 더 좋은 방법이 있다면 알려주시면 감사하겠습니다.

테스트 코드는 저번 pr의 로그인에 대한 기능입니다. 처음 테스트 코드를 작성해봤는데 아직 미숙한점이 많습니다. 
잘못된 점이 있으면 많이 조언해주세요!

2022-06-04 13:49 UTC, yyy9942 requested changes
고생하셨습니다~ 리뷰 확인 부탁드려요 :)

2022-06-04 13:49 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        memberService.deleteMember(principalDetails.getUsername());
`.deleteMember`또한 단순히 회원을 삭제하는 역할의 메서드로 보입니다. 검증이나 다른 역할도 할 수 있을텐데 좀 더 명시적인 메서드이름으로 변경해주세요.

2022-06-04 13:49 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        return new ProfileResponse(member);
조금 어려운 주제일 수 있지만 고민해보셨으면 해서 적습니다.

`duplicateIdChecking(profileUpdateRequest.getMemberId());` 이후 56번째 줄인 `member.updateProfile`을 실행하기 전 다른 요청으로 인해 중복된 ID가 이미 생길 수 있습니다. 

MySQL에서는 SELECT FOR UPDATE가 아닐 경우 일반 SELECT문의 경우 락이 잡혀있는 레코드라 하더라도 조회가 됩니다. 그렇기 때문에 `duplicateIdChecking(profileUpdateRequest.getMemberId());`를 했다고 하더라도 `member.updateProfile`을 하기 전에 다른 커넥션을 가진 곳에서 먼저 ID를 선점해서 Update를 할 수 있어요

https://techblog.woowahan.com/2631/ 요기를 참고해주시면 좋을듯하고, 이부분은 상당히 난이도가 있는 부분이니 일겅보시고 질문해주세요

2022-06-04 13:49 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    }
내부 동작을 보면 seq빼고 다 바꾸는듯한데요, 이건 Patch 보다는 Put 액션이 더 적절한것 같습니다

2022-06-04 13:49 UTC, yyy9942 commented on src/test/java/individual/freshplace/config/jwt/LoginTest.java
>                  .password(passwordEncoder.encode("testPw"))
이렇게 공통 멤버를 만든다면, memberId와 password를 테스트클래스 어딘가에 상수로 두고 상수를 사용하여 테스트하는게 좋을것 같네요. testId1을 testId2로 바꾸면 모든 테스트에서 다 testId1을 testId2로 바꿔주어야 할 것이니까요

2022-06-04 13:49 UTC, yyy9942 commented on src/test/java/individual/freshplace/config/jwt/LoginTest.java
>      public void setup() {
Junit5에서는 메서드에 public을 빼도 잘 작동합니다. public을 빼는게 컨벤션이기도 합니다

2022-06-05 01:42 UTC, jinyoungchoi95 reviewed
간단하게 리뷰 남겨보았습니다~

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +@Slf4j
쓰지 않고 있는 어노테이션인 것 같네요 :)

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        return new ResponseEntity<>(memberService.findMember(principalDetails.getUsername()), HttpStatus.OK);
`ResponseEntity.ok(emberService.findMember(principalDetails.getUsername());`

new 말고 ResponseEntity에서 제공하는 빌터패턴을 활용해보세요 :)

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/dto/profile/ProfileResponse.java
> +@NoArgsConstructor
사용하지 않고 기본 스펙에 의해 기본생성자가 필요한것이라면 private로 막아두는게 좋을 것 같네요 :)

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/dto/profile/ProfileResponse.java
> +    }
"개인 취향이 매우 담긴 의견이지만"

저는 생성자는 온전히 클래스에 해당하는 필드만 받고, 필드를 직접 바로 연결해주는 기능으로써만 존재해야한다라고 생각해요.
생성자가 Member를 받아 getter를 써서 매핑을 하게되는 순간 `생성자는 객체의 생성만을 담당해야한다`에서 `Member를 분석하여 객체를 생성한다`라는 기능 확장이 되어버리는 것 같다라는 생각이 많이 들어서요.

보통은 idea에서 제공하는 필드 매핑 생성자만 사용하고, 현재와 같은 케이스에서는
```java
public static ProfileResponse from(final Member member) {
    return new ProfileResponse(
        member.getMemberId(),
        member.getMemberName(),
        member.getPhoneNumber(),
        member.getEmail(),
        member.getMemberBirth(),
        member.getGradeCode().getGradeName()
    );
}
```
와 같은 형태의 정적팩토리메소드를 선호하는 편입니다 :) 참고차 봐주세요~

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/dto/profile/ProfileResponse.java
> +}
eol문제가 계속 발생하네요~

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +    @Transactional(readOnly = true)
사람마다 다르지만 요즘은 `@Transactionl(readOnly = true)`를 클래스단에 두고 `readOnly`옵션이 없어야하는 메소드들에 따로 `@Transactional`을 걸기도 합니다 :)

2022-06-05 01:42 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.USERNAME_NOT_FOUND, memberId));
계속해서 반복되는 find 기능인것 같은데 공통된 부분을 메소드로 뺴는건 어떨까요?

2022-06-07 12:12 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        return new ResponseEntity<>(memberService.findMember(principalDetails.getUsername()), HttpStatus.OK);
> `ResponseEntity.ok(emberService.findMember(principalDetails.getUsername());`
> 
> new 말고 ResponseEntity에서 제공하는 빌터패턴을 활용해보세요 :)

네~

2022-06-07 13:46 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/profile/ProfileResponse.java
> +    }
> "개인 취향이 매우 담긴 의견이지만"
> 
> 저는 생성자는 온전히 클래스에 해당하는 필드만 받고, 필드를 직접 바로 연결해주는 기능으로써만 존재해야한다라고 생각해요. 생성자가 Member를 받아 getter를 써서 매핑을 하게되는 순간 `생성자는 객체의 생성만을 담당해야한다`에서 `Member를 분석하여 객체를 생성한다`라는 기능 확장이 되어버리는 것 같다라는 생각이 많이 들어서요.
> 
> 보통은 idea에서 제공하는 필드 매핑 생성자만 사용하고, 현재와 같은 케이스에서는
> 
> ```java
> public static ProfileResponse from(final Member member) {
>     return new ProfileResponse(
>         member.getMemberId(),
>         member.getMemberName(),
>         member.getPhoneNumber(),
>         member.getEmail(),
>         member.getMemberBirth(),
>         member.getGradeCode().getGradeName()
>     );
> }
> ```
> 
> 와 같은 형태의 정적팩토리메소드를 선호하는 편입니다 :) 참고차 봐주세요~

정적팩토리 메소드 활용해보겠습니다!

2022-06-08 04:39 UTC, suyeonkwong commented on src/test/java/individual/freshplace/config/jwt/LoginTest.java
>      public void setup() {
> Junit5에서는 메서드에 public을 빼도 잘 작동합니다. public을 빼는게 컨벤션이기도 합니다

네!!

2022-06-08 05:07 UTC, suyeonkwong commented on src/test/java/individual/freshplace/config/jwt/LoginTest.java
>                  .password(passwordEncoder.encode("testPw"))
> 이렇게 공통 멤버를 만든다면, memberId와 password를 테스트클래스 어딘가에 상수로 두고 상수를 사용하여 테스트하는게 좋을것 같네요. testId1을 testId2로 바꾸면 모든 테스트에서 다 testId1을 testId2로 바꿔주어야 할 것이니까요

네~~

2022-06-08 05:21 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    }
> 내부 동작을 보면 seq빼고 다 바꾸는듯한데요, 이건 Patch 보다는 Put 액션이 더 적절한것 같습니다

넵

2022-06-08 05:33 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    }
> `@AuthenticationPrincipal PrincipalDetails principalDetails`로 PrincipalDetails를 가져오는건 괜찮은 방법입니다. SecurityContextHolder에 저장된 Member의 정보를 조회하는것이기 때문에 문제라고 할만한 부분은 없어요~
> 
> 그리고 SecurityContextHolder에 저장된 멤버데이터가 아니라 DB에서 Member를 한번더 조회한 후 DTO로 변환하는 부분도 괜찮네요. SecurityContextHolder 부분에 저장된 멤버데이터도 어떻게보면 캐싱된 데이터이기 때문에 명확하게 멤버의 정보를 조회할 때에는 DB에 저장된 실제 데이터를 한번 더 조회해주는것이 좋습니다 💯 💯 💯
> 
> 다만 여기서 애매한 부분이라면 `memberService.findMember` 의 메서드 명일거 같아요. Member를 가져오는게 아니라 Profile 정보를 가져오는것이기 떄문에, 이부분은 `findMemberProfile`과 같이 바꾸거나 컨트롤러에서 Member를 조회한 후 DTO로 변경해주는것도 나쁘지 않아보입니다.

컨트롤러에서 member를 조회한 후 dto로 변경하도록 하겠습니다.

2022-06-08 08:55 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    @GetMapping("/member/mypage/profile")
> 헷갈리면 mypage만 제거해도 될거같아요. 이건 view를 리턴하는것도 아니고, 리소스에 대한 요청이라면 mypage라는 영역이 필요하지 않아보입니다~

/members/profile로 변경하겠습니다.

2022-06-09 10:38 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        memberService.saveMember(signupRequest.toServiceDto(passwordEncoder.encode(signupRequest.getPassword())));
> 컨트롤러 레벨의 메서드를 좀 더 명시적인 signup으로 바꿔주신건 좋은 부분으로 보여요!
> 
> 다만, memberService의 `public void saveMember(SignupRequest signupRequest)` 의 경우 Member를 저장하는 역할만 하지는 않고 있어요. 예를 들면
> 
> * `duplicateIdChecking` 메서드를 통한 중복체크 검증
> * DiscountByGrade 검증 및 Member에 세팅
> 
> 위와 같은 여러 역할들을 하고있기 때문에 `saveMember`라는 메서드명은 적합하지 않아 보입니다. 메서드 이름으로 유추하자면 단순히 멤버를 저장만 하는 역할로 오해할 수 있어요.
> 
> 그리고 `signupRequest.toServiceDto(passwordEncoder.encode(signupRequest.getPassword()))`와 같은 메서드도 적합하지 않을 수 있는것이 request DTO에서 toServiceDto와 같은 레이어 이름을 가지고 메서드명을 만드는것은 어색할 수 있다고 봅니다. 패스워드에 대한 인코딩또한 컨트롤러에서 해주어야하는 역할이 아닌 서비스레이어에서 진행해야하는 **비즈니스 로직**으로 볼 수 있지 않을까요?
> 
> member Request를 서비스 레이어로 넘긴 후 서비스 레이어에서 해당 request를 Member의 형태로 패스워드를 인코딩해고, 여러가지 세팅을 해서 저장하는 흐름을 만들어보는건 어떨까요?

패스워드 인코딩하는 부분은 서비스에서 처리하도록 변경하겠습니다! 그리고 메소드 이름도 변경하도록 하겠습니다

2022-06-09 10:43 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.USERNAME_NOT_FOUND, memberId));
> 계속해서 반복되는 find 기능인것 같은데 공통된 부분을 메소드로 뺴는건 어떨까요?
네 ㅎㅎ

2022-06-09 12:32 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/profile/ProfileResponse.java
> +}
> eol문제가 계속 발생하네요~

LF로 변경하겠습니다!!

2022-06-12 00:31 UTC, yyy9942 requested changes

2022-06-17 12:53 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        Member member = memberService.findMember(principalDetails.getUsername());
> 직렬화시 참조지옥이 일어날 수 있기 때문에 dto에 필요한 필드만 담아서 순환참조가 일어나지 않도록 해야 한다는 사실!!! 주의 하겠습니다

2022-06-18 06:09 UTC, yyy9942 requested changes
락 도입의 시도는 좋지만, 아직 보완할점이 여러가지 보입니다 :)

2022-06-18 06:09 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        return ProfileResponse.from(member);
이렇게 매개변수가 하나이며, 별도의 이름이 필요하지 않은 팩토리 메서드의 경우 생성자로 변경하시는게 더 깔끔해보일 수 있다는점도 참고해주세요 :) 요건 바꾸지 않아도 됩니다.
```
new ProfileResponse(member);
```

2022-06-18 06:09 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +            memberRepository.flush();
`memberRepository.flush();`는 왜 호출하는건가요?

2022-06-24 10:57 UTC, jinyoungchoi95 reviewed
lock 기능이 인상깊네요 :)

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +        return new ResponseEntity(HttpStatus.OK);
```suggestion
        return ResponseEntity.ok().build();
```
로도 수정할 수 있겠네요 :)

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    }
`GlobalExceptionHandler`에서 관리해도 되지 않을까요?

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/dto/profile/ProfileResponse.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
다른 dto들도 접근제어자를 수정해주면 좋을 것 같네요 :)

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/entity/Address.java
>  @NoArgsConstructor
`@NoArgsConstructor(access = AccessLevel.PROTECTED)` 👀

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.BAD_CODE, GradeCode.CODE_GRADE_GENERAL));
`ErrorCode`와 `GradeCode`를 따로 분리하여 관리하는 이유가 있을까요?

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
Object로 반환하는 이유가 있을까요?

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/test/java/individual/freshplace/service/MemberServiceTest.java
> +public class MemberServiceTest {
🤔

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +        }
메소드 단위로 분리해도되는 기능인 것 같네요 :)

2022-06-24 10:57 UTC, jinyoungchoi95 commented on src/main/java/individual/freshplace/service/MemberService.java
> +                profileUpdateRequest.getMemberBirth());
(외적으로 참고차 이야기하는 내용이니 적용안하셔도됩니다)

member를 update하기 위해 memberid, name, number, email....을 받고있는데요. 

제가 지금 해당 코드를 같이 협업하여 개발하는 개발자라고 생각해볼게요.

`updateProfile()`의 모든 인자는 String으로 해당 메소드를 다른 곳에서 제가 사용하려고 하면 "순서"에 맞게 "아주 잘" 입력해주어야해요.
근데 예를들어 실수로 `phoneNumber`와 `email`의 순서를 잘못 넣어도 현재는 제가 어떻게 코드를 짜느냐에 따라서 프로덕션 코드에 그대로 담기게 되는거죠. 그게 그대로 반영되면 member의 정보가 email과 phonenumber가 순서에 맞지 않게 업데이트 되겠네요. (물론 테스트를 잘짜면 그런일이 발생하진 않겠지만요)

그럼 현재 상태를 개선할 수 있는 방법은 어떤 것이 있을까요?

2022-06-26 00:37 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/MemberController.java
> +
컨트롤러 레벨에 비즈니스로직인 락을 잡는행위가 들어갔어요. 이러한 락을 잡는 행위는 서비스레이어로 변경해주세요

2022-07-09 14:54 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +    }
이 락 방식에 대해 설명해주실 수 있으신가요?

2022-07-09 14:54 UTC, yyy9942 commented on src/test/java/individual/freshplace/service/MemberServiceTest.java
> +    @DisplayName("일반 회원가입")
테스트의 조건, 성공조건, 실패조건을 알 수 있도록 네이밍을 변경해주세요~

2022-07-14 04:38 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.BAD_CODE, GradeCode.CODE_GRADE_GENERAL));
> `ErrorCode`와 `GradeCode`를 따로 분리하여 관리하는 이유가 있을까요?

ErrorCode는 status와 message를 가지고 있고 GradeCode는 상수 형태로 값만 가지고 있습니다! 사용목적도 달라서 따로 분리해서 관리하는게 좋을것같다고 생각했습니다.

2022-07-14 04:51 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +        }
> 메소드 단위로 분리해도되는 기능인 것 같네요 :)

if문에서 발생하는 예외가 달라서 메소드로 따로 분리하기가 힘들것같습니다ㅠㅠ

2022-07-14 05:18 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +                profileUpdateRequest.getMemberBirth());
> 그럼 현재 상태를 개선할 수 있는 방법은 어떤 것이 있을까요?
메서드에 String인자를 하나하나 넘기는 것이 아니라 변경할 dto를 넘겨서 entity에서 update해주는 방법이 생각납니다!

2022-07-14 05:25 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/MemberController.java
> +    }
> `GlobalExceptionHandler`에서 관리해도 되지 않을까요?

네 GlobalExceptionHandler 에서 관리하는게 좋을거같습니다!

2022-07-14 05:58 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/GlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
> Object로 반환하는 이유가 있을까요?

handleMethodArgumentNotValid() 가 ResponseEntityExceptionHandler의 Override된 메소드여서 Object로 반환하였습니다

2022-07-14 06:48 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +    }
> 이 락 방식에 대해 설명해주실 수 있으신가요?

getEnclosingMethod() 사용하려고 로컬메서드를 그냥 가져오면 자꾸 null이떠서 익명 클래스 만들어서 사용했는데 그냥 메서드 네임을 수기로 적는게 나을것같습니다.

2022-07-14 15:49 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/lock/UserLevelLock.java
> +    public <T> T lockProcess(String lockName, Supplier<T> supplier) {   //메서드 이름 바꾸기 소문자로 시작
이번거는 머지하시고, 락 이름을 별도의 상수클래스에 모아놓고 관리하는걸로 변경하면 좋을거같습니다

2022-07-17 01:06 UTC, yyy9942 approved these changes

2022-07-17 05:39 UTC, merged