주문 요청에 대한 성공
E-TF/Fresh-place pull request #31
Opened 2022-12-07 19:12 UTC by suyeonkwong

2022-12-09 12:56 UTC, yyy9942 requested changes

2022-12-09 12:56 UTC, yyy9942 commented on src/main/resources/application-db.yml
> +    host: localhost
별도 redis 서버는 구축하지 않은건가요?

2022-12-15 09:13 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/AsyncConfig.java
> +    }
> 1. ExecutorService를 사용하지 않고 고정된 값으로 직접 스레드풀을 만든 이유가 있으신가요?
> 2. 이 스레드개수와 큐의 크기는 아주 작은 성능인 서버와 좋은 성능의 서버에서 모두 동일한 크기여야할까요?

고정된 크기의 스레드 풀을 생성해놓고 사용하면 다른 메서드에서 비동기 작업이 필요할 때 매번 스레드를 생성하지 않아도 된다고 생각해서 사용했습니다 (new FixedThreadPool 등등... ). 그런데 2번 질문은 잘 이해가 가지 않습니다. 저 사이즈 자체가 서버의 성능에 영향을 줄 만큼 크기가 크다고 생각하지 못했는데요.. 서버의 성능에 따라서 스레드 사이즈를 적절히 조절해서 사용해야 한다고 이해했는데 제가 이해한것이 맞을까요?

2022-12-15 09:17 UTC, suyeonkwong commented on src/main/resources/application-db.yml
> +    host: localhost
> 별도 redis 서버는 구축하지 않은건가요?

배포 서버에는 redis 구축을 했지만 보안문제로 외부에서 접근이 불가능 하다고 해서 진짜 redis 서버를 고정으로 하나 딱 만들고 어디서든 접근하게 하려면 ElastiCache는 사용하면 안될것같습니다..

2022-12-15 09:41 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/order/OrderRequest.java
> +}
> 이 클래스가 리플랙션 없이 멤버변수에 값을 할당(초기화) 할 수 있는 방법이 있을까요?

@Getter를 통해 ObjectMapper가 @RequestBody를 만나면 값을 주입시키는 방식만 알고있었는데,, 다른 방법은 잘 모르겠습니다. 찾아보겠습니다!

2022-12-15 09:44 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/OrderService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.BAD_VALUE, id.toString()));
> 없으면 throw한다는 점에서 이 메서드는 find가 아닌 get 네이밍이 적절해보입니다.

getById는 EntityNotFoundException을 발생시키는데 OrderRepository에서도 getById를 사용하는것이 적절할까요? ㅠㅠ
레파지토리에서 findById를 사용하는데 저 메서드 네임이 get이면 혼란스러울것같습니다. ㅠ ㅠ ㅠ

2022-12-16 13:35 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/AsyncConfig.java
> +    }
네. 서버에 따라서 스레드풀을 다르게 가져가는게 더 효율적일 수 있겠죠.
CPU 코어가 4개인 서버에서 4개짜리 스레드풀을 돌리는것과 CPU 코어가 16개인 코어에서 동일한 스레드풀을 돌린다면 병렬처리를 더 잘할 수 있음에도 불구하고 스레드풀이 작아서 더 나은 성능을 못낼수도 있어요.
ExecutorService에서 cachedThreadpool을 만드는 방식을 한번 확인해보시겠어요?

2022-12-22 11:54 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/OrderService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.BAD_VALUE, id.toString()));
repository에서 findBy--를 사용하는건 찾을수 있을수도, 없을수도 있기 때문입니다. 서비스 레이어에서는 이게 값이 있는지 없는지 검사하는 비즈니스 로직을 줄 수 있기 때문에 get-- 또는 findBy-- 로 구분을 명확하게 해주시는게 추후 코드 가독성이나 사용측면에서 관리하기 편해질거에요

2022-12-22 11:55 UTC, yyy9942 commented on src/main/resources/application-db.yml
> +    host: localhost
그러면 실제 서버에서도 redis 접근할 때 로컬 레디스로 접근하나요?

2022-12-23 05:03 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/AsyncConfig.java
> +    }
> 네. 서버에 따라서 스레드풀을 다르게 가져가는게 더 효율적일 수 있겠죠. CPU 코어가 4개인 서버에서 4개짜리 스레드풀을 돌리는것과 CPU 코어가 16개인 코어에서 동일한 스레드풀을 돌린다면 병렬처리를 더 잘할 수 있음에도 불구하고 스레드풀이 작아서 더 나은 성능을 못낼수도 있어요. ExecutorService에서 cachedThreadpool을 만드는 방식을 한번 확인해보시겠어요?

제가 사용하고 있는 CompletableFuture는 ForkJoinPool을 사용해서 현재 빈등록하고 있는 Executor를 사용하지 못하네요 ㅠㅠ

2022-12-23 10:43 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/OrderService.java
> +                .orElseThrow(() -> new WrongValueException(ErrorCode.BAD_VALUE, id.toString()));
> repository에서 findBy--를 사용하는건 찾을수 있을수도, 없을수도 있기 때문입니다. 서비스 레이어에서는 이게 값이 있는지 없는지 검사하는 비즈니스 로직을 줄 수 있기 때문에 get-- 또는 findBy-- 로 구분을 명확하게 해주시는게 추후 코드 가독성이나 사용측면에서 관리하기 편해질거에요

findBy 는 찾다 (찾거나 찾지못할 경우 Optional로 null을 리턴하는 선택이 있음.) , getBy 는 얻다 (무조건 얻어야 하고 null허용 안함.) 의 차이가 있으니 현재 저 서비스 메서드는 throw한다는 점이 null을 허용할 수 없다는 의미니까 get이 더 적절하다는 의미이겠죠 ㅎㅎㅎ 이제 이해했습니다. get으로 변경하는게 더 좋은 선택인것같습니다.

2022-12-23 10:45 UTC, suyeonkwong commented on src/main/resources/application-db.yml
> +    host: localhost
> 그러면 실제 서버에서도 redis 접근할 때 로컬 레디스로 접근하나요?

아뇨 지금은 어쩔 수 없이 로컬에선 로컬로 실 서버는 aws redis 로 따로 접근됩니다. (로컬에서 aws redis 접근 시도했지만 보안때문에 실패 ㅠㅠ )실 서버랑 로컬 서버랑 동시에 접근 할 수 있도록 별도의 서버를 어떤 식으로 둬야 할지 잘 모르겠습니다.

2022-12-30 07:16 UTC, yyy9942 approved these changes
고생하셨습니다. 머지해주세요~

2023-01-01 19:49 UTC, merged