주문정보 조회하기
E-TF/Fresh-place pull request #32
Opened 2022-12-10 12:39 UTC by suyeonkwong

2022-12-13 02:23 UTC, yyy9942 requested changes

2022-12-13 02:23 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/OrderController.java
> +    }
단순 200 OK값과 함께 내려주려한다면 ResponseEntity를 쓰지 않으셔도 됩니다.
return값으로 List만 주셔도 똑같은 리턴값이 나올거에요.

2022-12-13 02:23 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/kakaopay/KakaoPayOrderDetailsResponse.java
> +    @ToString
이건 왜 추가하신건가요?

2022-12-13 02:23 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/payment/Receipt.java
> +@ToString
`@ToString`의 경우 순환참조 발생시 StackOverflow 발생 여지가 있지 않을까요?

2022-12-13 02:23 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Payment.java
>      private Order order;
이부분을 LAZY로 두지 않는다면 N+1이 발생할 수 있을듯한데 어떻게 생각하시나요?

2022-12-14 17:43 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/OrderController.java
> +    }
> 단순 200 OK값과 함께 내려주려한다면 ResponseEntity를 쓰지 않으셔도 됩니다. return값으로 List만 주셔도 똑같은 리턴값이 나올거에요.

ResponseEntity를 사용하는게 컨벤션인줄 알았습니다. ㅠㅠ 그럼 return값이 void인 경우나 List를 사용하지 않는 경우도 200OK면 ResponseEntity를 사용하지 않아도 되는걸까요? 아니면 List일 경우만 List자체를 return하는것일까요???

2022-12-14 17:44 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/kakaopay/KakaoPayOrderDetailsResponse.java
> +    @ToString
> 이건 왜 추가하신건가요?

값 추적하면서 사용했는데 현재는 사용하지 않으므로 제거하도록 하겠습니다. ㅜㅜ

2022-12-14 17:57 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/payment/Receipt.java
> +@ToString
> `@ToString`의 경우 순환참조 발생시 StackOverflow 발생 여지가 있지 않을까요?
양방향 관계에서 @ToString을 지양해야 하는것을 알았습니다! 그런데 dto에서도 지양해야 하는지 여쭙고싶습니다.

2022-12-14 17:57 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/payment/Receipt.java
> +@ToString
> > `@ToString`의 경우 순환참조 발생시 StackOverflow 발생 여지가 있지 않을까요?
> > 양방향 관계에서 @tostring을 지양해야 하는것을 알았습니다! 그런데 dto에서도 지양해야 하는지 여쭙고싶습니다.

이 부분도 사용 목적이 없으므로 지우도록 하겠습니다! 사용하지 않는 어노테이션은 절대로 지우기!!

2022-12-14 19:47 UTC, suyeonkwong commented on src/main/java/individual/freshplace/entity/Payment.java
>      private Order order;
> 이부분을 LAZY로 두지 않는다면 N+1이 발생할 수 있을듯한데 어떻게 생각하시나요?

Payment가 연관관계 주인인데 주 테이블이 Order라서 Order에서 payment조회 시 n+1이 발생할것같습니다.

2022-12-16 13:16 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/OrderController.java
> +    }
@suyeonkwong 네 200 ok 일 경우 `ResponseEntity`는 생략해도 됩니다. 그냥 Object 또는 void를 리턴해주면 됩니다

2022-12-16 13:18 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/payment/Receipt.java
> +@ToString
@suyeonkwong 사용목적이 없을때는 사용하지 않는것이 좋습니다.

2022-12-16 13:26 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Payment.java
>      private Order order;
@suyeonkwong `@OneToOne` 양방향 연관 관계에서 연관 관계의 주인이 아닌 쪽 엔티티를 조회할 때, Lazy로 동작할 수 없습니다. 사용하실거라면 단방향으로 만드는것도 좋을것이고, 양방향으로 설정한다면 N+1을 감수하고 사용해야하니 이부분을 한번 확인해보세요

2022-12-16 13:27 UTC, yyy9942 commented
@suyeonkwong 아직 수정사항이 올라오지 않은듯합니다. 이 브랜치에 수정하고계신가요?

2022-12-17 18:16 UTC, suyeonkwong commented
> @suyeonkwong 아직 수정사항이 올라오지 않은듯합니다. 이 브랜치에 수정하고계신가요?

아뇽 따로 수정하고 있습니다. 후딱 올리겠습니다.

2022-12-17 18:32 UTC, suyeonkwong commented on src/main/java/individual/freshplace/entity/Payment.java
>      private Order order;
> @suyeonkwong `@OneToOne` 양방향 연관 관계에서 연관 관계의 주인이 아닌 쪽 엔티티를 조회할 때, Lazy로 동작할 수 없습니다. 사용하실거라면 단방향으로 만드는것도 좋을것이고, 양방향으로 설정한다면 N+1을 감수하고 사용해야하니 이부분을 한번 확인해보세요

전 Order에서 Payment를 참조하도록 하고 싶습니다! 단방향으로 Order를 외래키 주인으로 DB를 변경하면 문제가 될까요??

2022-12-17 18:35 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/OrderController.java
> +    }
> @suyeonkwong 네 200 ok 일 경우 `ResponseEntity`는 생략해도 됩니다. 그냥 Object 또는 void를 리턴해주면 됩니다

Put요청이나 Patch요청이 성공했을 때는 201처럼 정해져있는 다른 상태코드가 있을까요??

2022-12-22 11:52 UTC, yyy9942 requested changes
테스트코드 추가 부탁드립니다

2022-12-22 11:52 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/AccountController.java
> +@Controller
왜 Controller로 변경하신건가요? 이렇게되면 view resolver를 타게되어 view를 찾을텐데 API 서버에서 요걸 사용할 일이 없지 않을까싶습니다

2022-12-23 10:18 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/AccountController.java
> +@Controller
> 왜 Controller로 변경하신건가요? 이렇게되면 view resolver를 타게되어 view를 찾을텐데 API 서버에서 요걸 사용할 일이 없지 않을까싶습니다

return 값이 void면 mapping 이름의 view를 찾게 되는데 제가 왜 이걸 변경했는지 기억이 나질 않습니다. 주의학겠습니다...

2022-12-23 10:27 UTC, suyeonkwong commented
> 테스트코드 추가 부탁드립니다

단순 조희에 대한 기능에 대해서 비니지스에 의미가 있는 부분을 딱히 찾지 못하겠습니다. ㅠㅠ

2022-12-30 07:55 UTC, yyy9942 approved these changes
머지하셔도 좋습니다!

2023-01-01 19:47 UTC, merged