order cancel
E-TF/Fresh-place pull request #34
Opened 2023-01-07 09:24 UTC by suyeonkwong

2023-01-14 06:30 UTC, yyy9942 requested changes

2023-01-14 06:30 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/OrderController.java
> +    }
1. 1회성으로 저장 후 바로 리턴한다면 변수에 저장할 필요가 없을거같아요. 바로 리턴문으로 적어주는게 더 깔끔할겁니다.
2. 만약 변수를 선언한다고 해도, 불변성을 위해 final 선언을 해주시는게 좋습니다. 모든 변수는 final을 붙혀서 선언해주세요

2023-01-14 06:30 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/kakaopay/KakaoPayPaymentCancelResponse.java
> +    private String payload;
가능하다면 DTO의 변수는 final을 붙혀서 불변성을 유지해주세요. setter가 없는것도 괜찮습니다만 컴파일레벨에서 불변성을 유지해주는 키워드는 final만큼 명시적인게 없습니다

2023-01-14 06:30 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Order.java
> +    }
상태를 변경시키는 행위는 별도 서비스클래스 or 레포지토리 레벨에 있어야합니다.
이 메서드가 트랜잭션 밖에서 호출될 수 있는 여지를 주기때문이기도 하고, MVC의 계층에서는 도메인이 이러한 비즈니스 로직을 가지면 컨트롤러 - 서비스 - 레포지토리의 계층이 깨지기 때문입니다.

2023-01-14 06:30 UTC, yyy9942 commented on src/main/java/individual/freshplace/entity/Payment.java
> +    }
이부분도 마찬가지로 서비스 또는 레포지토리 계층으로 가야합니다

2023-01-14 06:30 UTC, yyy9942 commented on src/test/java/individual/freshplace/service/OrderServiceTest.java
> +    @DisplayName("주문취소 시 주문상태와 결제상태가 모두 변경되는지 확인")
'모두 변경되는지 확인' 이라고 하면 어떤값이 어떻게 변경되어야 성공인지, 이 테스트가 실패한다면 왜 실패했는지 알기 어렵습니다.
좀 더 가독성좋게 아에 단언문으로 적어주시면 좋을거같아요.
ex) 주문 취소시 주문상태는 ~~로 변경된다

2023-01-14 06:30 UTC, yyy9942 commented on src/test/java/individual/freshplace/service/OrderServiceTest.java
> +        Assertions.assertEquals(payment.getPaymentStatusCode(), PaymentStatus.CANCEL);
만약 이 3가지 테스트 단언문중 첫번째 테스트에서 실패가 일어날 시 아래에 남은 두개의 단언문은 실행되지 않습니다. 이런 경우 테스트 실패를 수정하고도 다음테스트가 또 실패하는 등 불편이 발생할 수 있기때문에 모든 테스트를 다 실행하는 [assertAll](https://www.javaguides.net/2018/09/junit-5-assertall-example.html)으로 감싸주는게 좋습니다.

2023-01-18 05:42 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/OrderController.java
> +    }
> 1. 1회성으로 저장 후 바로 리턴한다면 변수에 저장할 필요가 없을거같아요. 바로 리턴문으로 적어주는게 더 깔끔할겁니다.
> 2. 만약 변수를 선언한다고 해도, 불변성을 위해 final 선언을 해주시는게 좋습니다. 모든 변수는 final을 붙혀서 선언해주세요

헐 ! 네!!

2023-01-28 15:29 UTC, yyy9942 approved these changes
잘 수정해주신거 확인하였습니다. 머지해주세요~

2023-01-28 16:28 UTC, merged