배송지 조회, 등록
E-TF/Fresh-place pull request #4
Opened 2022-07-20 12:05 UTC by suyeonkwong

이번 기능은 회원이 주문에 필요한 배송지를 등록하는 기능입니다. (주문 로직 아닙니다.)

현재 Controller - Service - Repository 이 구조를 사용하고있는데요  저는 그동안 각 계층이 하는 역할을 잘 구분하지 못하고 사용하고 있다는 생각을 하고있었습니다. 제가 고민하는 부분은 Service layer에서 다른 Service를 호출하는 것이 좋은지 아니면 Controller에서 해당 Service에서 필요한 entity를 가져와서 넘겨주는 것이 좋은지에 대한 부분입니다. 

    private final MemberService memberService;
    private final DeliveryAddressService deliverAddressService;

    @GetMapping
    public ResponseEntity<List<DeliveryAddressResponse>> getDeliveryAddresses(@AuthenticationPrincipal PrincipalDetails principalDetails) {
        final Member member = memberService.findMember(principalDetails.getUsername());
        return ResponseEntity.ok().body(deliverAddressService.getDeliveryAddresses(member));
    }

현재 DeliveryAddressController 에서 DeliveryAddressService외에도 MemberService를 의존하고 있는데 회원의 주소를 조회하기 위해 회원엔티티를 가져와서 DeliveryAddressService 로 넘겨주고있습니다. 

처음엔 DeliveryAddressService에서 getDeliveryAddresses()를 위해 필요한 Member의 Entity를 얻기 위해 MemberRepository를 직접 호출했습니다. 그런데 이럴 경우 이미 MemberService의 findMember()메서드가 가지고 있는 코드와 동일하여 재사용성이 떨어진다는 생각을 했습니다. 

그래서 두번째로  생각한 방법이 DeliveryAddressService에서 MemberService를 호출하기 였습니다.  그런데 문득 다른 분들은 Service를 어떻게 사용할지 궁금해서 찾아보다가 알게된 점이 한 Service에서 다른 Service들을 의존할 경우 해당 Service에서 다른 도메인이 필요해지고 해당 Service만의 역할을 충실하게 수행하기가 어렵다는 점이었습니다. 지금은 역할범위도 좁고 아직 다른 기능도 많이 없는 편이라 괜찮지만 나중에 여러 기능이 추가된다면 Service간의 결합에 의한 확장성에 대한 고민을 하게 되지 않을까 라는 생각을 했습니다.  

좋은 글들을 많이 읽어봤는데 이 문제에 대한 해결법이 Controller에서 여러 Service를 사용해서 각 Service에 대한 의존성을 낮추면서 역할에 충실하게 하는 법이었습니다.  그래서 저도 현재 코드처럼 Controller에서 다른 Service를 호출해서 필요한 entity를 가져오고 해당 Service에 넘겨주는 방법을 선택했습니다. 

그런데 또 여기서 고민되는 부분이 생겼습니다. 현재 Controller에서 호출한 Service의 return값인 domain (Member Entity)이 그대로 표현계층에 노출된다는 점이고, Controller에서 Service에 순수한 Entity를 넘기는 것은  

View <--dto--> controller <--dto--> Service <--domain--> Dao  <--domain--> DB

이런 계층 구조에 위반하는 행위라는 생각이 들었습니다. 그리고 저는 그동안 Controller에서 사용한 dto를 그대로 Service로 넘겨주고 있었는데 이럴 경우 다른 곳에서 해당 Service를 호출할때 또 Controller의 dto에 의존하게 된다는 점이었습니다. 

그래서 제가 생각한 결론이 새로운 Service용 dto를 생성해서 그곳에 필요한 Member(entity)를 멤버로 넣어주고 해당 dto를 Service로 넘기는 방법이었습니다. 

그런데 dto필드에 새로운 객체를 넣는다? 조합한다? 라는 생각이 좀 생소하기도 하고 이렇게 사용하는 경우를 본적이 없어서 혹시라도 문제가 되는 부분이 있을것같아서 여쭤보고싶습니다.

2022-07-22 03:24 UTC, yyy9942 commented
@suyeonkwong 수연님이 말씀하시는 패턴은 이미 디자인패턴으로 존재합니다. Facade 패턴을 찾아보시면 고민하고있는 내용을 좀 더 구체화하는데 도움이 될거에요.

2022-07-23 07:10 UTC, yyy9942 requested changes
리뷰 확인해주세요~ 고생하셨습니다.

2022-07-23 07:10 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/deliveryaddress/DeliveryAddressAddRequest.java
> +    private String contact;
밸리데이션을 건것은 좋은 시도입니다만 길이 밸리데이션을 할 때 min값만 검증한다면 최대 글자수만큼 입력해도 유효하다고 판단할듯 합니다. max 글자수도 잡아주면 더 일관성있는 코드가 될 것으로 보여요.

추가적으로 에러메세지를 보여줄 것이라면 다른 유효성 검증 밸리데이션에도 에러메세지를 명시해주는것도 좋을듯합니다. 일부는 메세지를 명시했고 일부는 명시하지 않아서 일관성이 떨어질 수 있겠네요

2022-07-23 07:10 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/DeliveryAddressService.java
> +    }
JPA 메서드 쿼리를 위해 엔티티를 매개변수로 받아 사용하는듯한데요, 이럴경우 사용하는쪽에서 엔티티를 조회해온 후 넣어야하는 불편함이 있을 수 있어요.

이렇게 사용하시는건 어떤가요?
```
deliverAddressRepository.findAllByMemberId(memberId)
```

2022-07-23 07:10 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/MemberService.java
> +    public Member findMember(String memberId) {
1. 이부분 트랜잭션 propagation을 서포트로 하신 이유가 무엇인가요?
2. propagation - supports를 사용하면 트랜잭션이 어떻게 작동하게될까요?

2022-07-30 07:38 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/DeliveryAddressController.java
> +        return ResponseEntity.ok().body(deliverAddressService.getDeliveryAddresses(member));
> 여기서 Member는 엔티티로 보이는데요, 엔티티를 컨트롤러레벨로 꺼내는것이나 다른 서비스의 인자로 엔티티를 넘기는것 모두 트랜잭션 외부로 엔티티를 꺼낸 것이기 때문에 좋지 않은 행위입니다.
> 
> 이미 끝난 트랜잭션에서 생성된 엔티티를 다른트랜잭션 안으로 끌고들어가면 데이터 불일치가 발생할 여지가 있고, 트랜잭션 외부로 엔티티를 꺼내면 발생하는 문제는 이전 PR에서도 여러번 언급한적 있으니 요부분은 지양해주세요.

엔티티는 트랜잭션 사용 계층인 서비스 레이어에서만 사용하도록 하겠습니다 ㅎㅎ

2022-07-30 11:03 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/deliveryaddress/DeliveryAddressAddRequest.java
> +    private String contact;
> 밸리데이션을 건것은 좋은 시도입니다만 길이 밸리데이션을 할 때 min값만 검증한다면 최대 글자수만큼 입력해도 유효하다고 판단할듯 합니다. max 글자수도 잡아주면 더 일관성있는 코드가 될 것으로 보여요.
> 
> 추가적으로 에러메세지를 보여줄 것이라면 다른 유효성 검증 밸리데이션에도 에러메세지를 명시해주는것도 좋을듯합니다. 일부는 메세지를 명시했고 일부는 명시하지 않아서 일관성이 떨어질 수 있겠네요

명시적인 에러 메시지를 지정해주고 min값과 max값을 지정하도록 하겠습니다!

2022-07-30 11:04 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/DeliveryAddressService.java
> +    }
> JPA 메서드 쿼리를 위해 엔티티를 매개변수로 받아 사용하는듯한데요, 이럴경우 사용하는쪽에서 엔티티를 조회해온 후 넣어야하는 불편함이 있을 수 있어요.
> 
> 이렇게 사용하시는건 어떤가요?
> 
> ```
> deliverAddressRepository.findAllByMemberId(memberId)
> ```

이부분은 Member와 DeliverAddress 엔티티가 양방향관계이므로 Member로 DeliverAddressList를 조회하도록 변경하였습니다 ㅎㅎ

2022-07-30 11:10 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/MemberService.java
> +    public Member findMember(String memberId) {
> 1. 이부분 트랜잭션 propagation을 서포트로 하신 이유가 무엇인가요?
> 2. propagation - supports를 사용하면 트랜잭션이 어떻게 작동하게될까요?

트랜잭션 전파속성을 사용한 이유는 퍼사드 패턴을 적용하기 전이었습니다! MemberService를 사용하는 다른 Service에서 이미 시작된 트랜잭션이 있으면 참여하고, 그렇지 않으면 트랜잭션 없이 진행시키기 위해 사용했는데 위에서 피드백 주신 컨트롤러 레벨로 엔티티를 꺼내는 문제점과 함께 퍼사드 구조로 변경하고 해결하였습니다!

2022-07-31 01:41 UTC, yyy9942 approved these changes
고생하셨습니다~ 머지해도 좋습니다

2022-08-01 16:12 UTC, merged