react 메인 페이지와 통신하기
E-TF/Fresh-place pull request #41
Opened 2023-02-14 18:30 UTC by suyeonkwong

+ 프론트 페이지 초기 설정입니다! 컨트롤러에서 데이터를 받아오게 하는것을 성공했습니다! 😆😆😆
그런데 현재 패키지 구조가 정상적인것인지 여쭤보고싶습니다. 원래 프론트 페이지를 '프로젝트명/src/main' 아래에 오게 하는것이 맞을까요?  🥺🥺

2023-02-15 13:48 UTC, yyy9942 requested changes
src/main/frontend/package-lock.json 파일의 경우 git 저장소에 올릴 필요가 없습니다. git에서 제거하신 후 .gitignore에 추가해주세요.

React를 프로젝트 내부에 세팅한다면 두가지 작업이 필요합니다.
1. Spring boot에서 오는 요청에 대해 React로 보내주어야합니다. index.html로 요청을 보내주어야합니다. 그래야 react 메인페이지가 뜨겠죠?
2. Spring boot 빌드시 react도 같이 빌드해주어야 합니다. maven을 사용한다면 pom.xml에, gradle을 사용한다면 build.gradle에 리액트 빌드 스크립트를 만들어주어야 합니다.

2023-03-18 14:11 UTC, yyy9942 requested changes

2023-03-18 14:11 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +    }, [])
`getItems`라는 함수를 정의할거면 `useEffect`외부에 지정해주셔야합니다. 그게 아니라면 아래처럼 바꿔주세요
```suggestion
    useEffect(() => {

            axios.get('/public/category')
                .then(data => {
                    setCategory(data.data);
                })

    }, [])
```

저 함수를 `useEffect` 내부 코드블럭에 지정하게된다면 어떤 이점도 없을것으로 보이네요. 저렇게 구현하신 이유가 있으실까요?

2023-03-18 14:11 UTC, yyy9942 commented on src/main/frontend/src/routes/Items.js
> +        console.log(items)
사용하지 않는 로그는 지워주세요

2023-03-18 14:11 UTC, yyy9942 commented on src/main/frontend/src/routes/Items.js
> +        getItems()
이부분도 마찬가지로 함수를선언할거라면 useEffect 내부가 아닌 외부에 선언해주셔야 합니다

2023-03-18 14:11 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +                .mvcMatchers(HttpMethod.GET, "/**").permitAll()
이걸 선언해버리면 모든 요청에 대해 권한을 안타서 문제가 되지 않을까요?

2023-03-18 14:11 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/HomeController.java
> +    }
테스트용도인거같은데 삭제해주세요~

2023-03-18 14:11 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/category/CategoryResponse.java
> +@NoArgsConstructor(force = true)
이건 왜 만드시는건가요? java 스펙상 들어가면 안될것으로 보입니다

2023-03-22 01:53 UTC, suyeonkwong commented
asdfasdf

2023-03-23 12:04 UTC, merged