회원가입 화면 구현하기
E-TF/Fresh-place pull request #42
Opened 2023-03-18 13:54 UTC by suyeonkwong

react-bootstrap + react hook form 조합으로 회원가입 폼을 구현했습니다. 
[https://react-hook-form.com/](url)

react-hook-form을 사용한 이유는 초반에 useState로 모든 컴포넌트를 관리하였으나 갯수가 늘어날 수록 가독성과 state로 부터 일어나는 여러 버그 추적이 까다롭다고 생각했기 때문입니다. 

또한 error 메시지와 register의 validation등의 검증 과정을 훨씬 수월하게 작성할 수 있었습니다.

2023-03-21 15:44 UTC, yyy9942 requested changes

2023-03-21 15:44 UTC, yyy9942 commented on src/main/frontend/src/routes/Detail.js
> +export default Detail
사용하지 않는 함수인듯합니다. 제거해주세요~

2023-03-21 15:44 UTC, yyy9942 commented on src/main/frontend/src/routes/Items.js
> +        axios.get('/public/items/category?codeEngName=' + categoryName)
`'/public/items/category?codeEngName=' + categoryName` 과 같은 문자열 덧셈의 경우 **Template literals** 기능을 사용해 가독성을 늘려줄 수 있습니다. 자세한 내용은 아래 링크를 확인해주세요. https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

2023-03-21 15:44 UTC, yyy9942 commented on src/main/frontend/src/routes/Signup.js
> +                console.log(response.data);
로그 제거해주세요

2023-03-21 15:44 UTC, yyy9942 commented on src/main/frontend/src/routes/Signup.js
> +                console.log(response.data);
추가적으로 팁을 말씀드리자면 이런 object형태의 데이터를 로그로 찍어서 확인하는것보다는 console에 있는 다양한 함수를 사용하면 좀 더 수월하게 확인이 가능합니다.

console.dir({object})
console.debug()
등등 여러가지 콘솔 명령어를 지원해주니 아래 문서를 확인해보고 로깅을 좀 더 편리하게 이용해보세요.
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

2023-03-21 15:44 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/HomeController.java
이 내용은 이전PR에서 수정을 요청한 부분으로 보이는데요, 다음부터 수정사항은 수정사항 요청한 브랜치에 올려주세요. 나중에 심각한 conflict가 발생하면 수정하기 정말 어려워집니다

2023-03-21 15:44 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/ItemService.java
> +        return Folder.IMAGE.getDirectoryName() + SLASH + Folder.GOODS.getDirectoryName() + SLASH + itemSeq.toString()
Tip. String문끼리 덧셈연산을 많이하면 이게 전체적으로 어떤 모양이 나올지 예측하기 어려운 경우가 있습니다.
이런 경우 `String.format()` 메서드를 사용하면 전체적인 모양을 알 수 있게됩니다. 한번 찾아서 적용해보세요

2023-03-22 02:01 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/HomeController.java
> 이 내용은 이전PR에서 수정을 요청한 부분으로 보이는데요, 다음부터 수정사항은 수정사항 요청한 브랜치에 올려주세요. 나중에 심각한 conflict가 발생하면 수정하기 정말 어려워집니다

네 ㅠㅠ 주의하겠습니다

2023-03-22 02:25 UTC, suyeonkwong commented on src/main/frontend/src/routes/Items.js
> +        axios.get('/public/items/category?codeEngName=' + categoryName)
> `'/public/items/category?codeEngName=' + categoryName` 과 같은 문자열 덧셈의 경우 **Template literals** 기능을 사용해 가독성을 늘려줄 수 있습니다. 자세한 내용은 아래 링크를 확인해주세요. https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

```
`/public/items/category?codeEngName=${categoryName}` 
```
'문자열 인터폴레이션' 이라는 기능을 사용하는 방법이 있다는것을 알게되었습니다!

2023-03-22 04:51 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/ItemService.java
> +        return Folder.IMAGE.getDirectoryName() + SLASH + Folder.GOODS.getDirectoryName() + SLASH + itemSeq.toString()
> Tip. String문끼리 덧셈연산을 많이하면 이게 전체적으로 어떤 모양이 나올지 예측하기 어려운 경우가 있습니다. 이런 경우 `String.format()` 메서드를 사용하면 전체적인 모양을 알 수 있게됩니다. 한번 찾아서 적용해보세요

`String.format("%s/%s/%s/%s",
                Folder.IMAGE.getDirectoryName(), Folder.GOODS.getDirectoryName(),itemSeq.toString(), Folder.RESIZE.getDirectoryName())` 이렇게 작성했더니 훨씬 예측하기 수월해졌습니다!

2023-03-22 04:54 UTC, suyeonkwong commented on src/main/frontend/src/routes/Signup.js
> +                console.log(response.data);
> 추가적으로 팁을 말씀드리자면 이런 object형태의 데이터를 로그로 찍어서 확인하는것보다는 console에 있는 다양한 함수를 사용하면 좀 더 수월하게 확인이 가능합니다.
> 
> console.dir({object}) console.debug() 등등 여러가지 콘솔 명령어를 지원해주니 아래 문서를 확인해보고 로깅을 좀 더 편리하게 이용해보세요. https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals
console도 log4j와 유사하게 log말고 다른 메서드 사용이 가능하군요!!! 근데 저렇게 로그를 사용하는것은 테스트 용도로만 사용하고 실제 코드에 작성하면 안되는것인지 여쭤보고싶습니다.

2023-03-22 04:55 UTC, suyeonkwong commented on src/main/frontend/src/routes/Signup.js
> +                console.log(response.data);
> 추가적으로 팁을 말씀드리자면 이런 object형태의 데이터를 로그로 찍어서 확인하는것보다는 console에 있는 다양한 함수를 사용하면 좀 더 수월하게 확인이 가능합니다.
> 
> console.dir({object}) console.debug() 등등 여러가지 콘솔 명령어를 지원해주니 아래 문서를 확인해보고 로깅을 좀 더 편리하게 이용해보세요. https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

console도 log4j와 유사하게 log말고 다른 메서드 사용이 가능하군요!!! 근데 저렇게 로그를 사용하는것은 테스트 용도로만 사용하고 실제 코드에 작성하면 안되는것인지 여쭤보고싶습니다.

2023-03-23 11:42 UTC, yyy9942 commented on src/main/frontend/src/routes/Signup.js
> +                console.log(response.data);
실제 프로덕션 서비스에 로그가 덕지덕지 찍히는데, 이 부분은 필요하지 않은 부분입니다. 사용자가 로그를 볼 일도 없고 로그에 불필요한 에러나 시스템 로그가 찍히면 사용자가 오해할 여지가 있기 때문에 제거해주는것이 좋습니다.

2023-03-23 11:43 UTC, yyy9942 approved these changes
확인하였습니다. 머지해주세요

2023-03-23 12:03 UTC, merged