백엔드에서 리프래시 토큰 도입하기
E-TF/Fresh-place pull request #43
Opened 2023-03-30 08:04 UTC by suyeonkwong

![untitled@1 25x (1)](https://user-images.githubusercontent.com/80368511/228759684-e25d7dca-e9da-49ba-b610-0217de2bbda5.png)

+ 개요 : 기존의 access token 사용방식에서 조금 더 보안과 사용성을 강화하기 위해 생각했었던 refresh token을 사용해보았습니다. 기존에 사용하던 필터들은 더이상 사용하지 않을것같아서 지웠습니다. 

 + 궁금할 수도 있는 부분 : 
    + 정확한 토큰 유효시간이 왜 바뀌었는지 : 첫번째 그림은 처음 설계 시 생각한 부분으로 access token 1시간 refresh token 1달로 작성되어있는데 access token 15분 refresh token 2주로 변경하였습니다. (서버가 토큰 재발급 해주는 요청이 더 필요하지만 짧은 시간만큼 탈취 걱정을 더 줄일 수 있기 때문입니다.)  --> 근데 15분은 너무 짧은 것 같다고 생각은 듭니다. 
    
    ![security-9](https://user-images.githubusercontent.com/80368511/228763100-9026f5d7-291a-4fc0-baec-620e66b8581e.png) 
     + AuthenticationFilter말고 AuthenticationProvider를 추가적으로 implements 한 이유 : 원래 spring security로그인 서비스에서 Authentication검증 시 ProviderManager가 AuthenticationProvider의 authentication() 메서드를 호출 하도록 설계되어있습니다. 
그러나 저같은 경우 프론트에서 아이디와 비밀번호 중 어떤것이 틀렸는지 사용자에게 alert를 띄우주고싶어서 AuthenticationProvider를 구현하여 다른 response를 리턴받도록 했습니다. 
     ```
        try {
                    userDetails = principalDetailsService.loadUserByUsername(memberId);
                } catch (UsernameNotFoundException e) {
                    throw new CustomAuthenticationException(ErrorCode.USERNAME_NOT_FOUND);
                }
                if (!passwordEncoder.matches(password, userDetails.getPassword())) {
                    throw new CustomAuthenticationException(ErrorCode.NOT_MATCH_PASSWORD);
                }
      ```

   

 + 고민거리 : access token재발급과 refresh token무효화 처리를 위해 refersh token을 저장시키기 위해 서버 스토리지가 필요했었는데 RDB에 저장하는 대신 원래 같이 사용하던 Redis에 저장했습니다. 

      refresh token사용자 검증을 위한 방법으로 처음 로그인했던 ip를 같이 저장해서 비교하는 방법이 있다는 사실을 알게 되었는 
      데 저는 ip를 저장하지 않고 재발급 시 access token을 받아서 해당 토큰을 통해 사용자 정보를 추출하여 refresh token의 이전 
      의 로그인한 사용자와 비교하는 방식을 선택했습니다. 
      
     ip를 검증하는 방법을 사용하는게 더 좋은 방법일까요? 재발급 시 그냥 아이디 검증으로만 사용자를 구분짓는게 위험한 것인 
     지 궁급합니다.

2023-04-07 11:46 UTC, yyy9942 requested changes
고생하셨습니다.
인증/인가 모듈에 대해 고민한부분이 보여 칭찬드리겠습니다.

수정사항 수정 후 다시 리뷰요청 해주세요~

2023-04-07 11:46 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +        if (authorization == null || !CookieUtils.exitsRefreshToken(httpServletRequest.getCookies())) {
tip. 이런 if 문에 들어가는 부분은 메서드로 분리하면 나중에 이 부분이 어떤걸 검증하는것인지 알기 편합니다.

2023-04-07 11:46 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +            return new TokenReissueResponse(jwtTokenProvider.createAccessToken(principalDetails));
이 부분은 메서드로 분리하면 가독성이 증가할것으로 보이네요. 토큰이 expire 되었으니 이에 대한 후속처리, 즉 신규 access 토큰 발급로직 메서드를 만들어 분리해보세요

2023-04-07 11:46 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +            throw new CustomAuthenticationException(ErrorCode.INVALID_TOKEN);
로그아웃을 시도하는데 token값이 잘못되었다면 클라이언트에서 해줄 수 있는게 있을까요? 클라이언트 입장에서는 가지고있는 리프레시토큰을 지우고, 서버에 리프레시토큰 삭제를 요청하고 끝일것으로 보입니다.

그러면 서버에서는 리프레시토큰이 있으면 지우고, 없으면 별다른 조치를 하지 않아도 무방할 것으로 보입니다.

2023-04-07 11:46 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +            if (Boolean.TRUE.equals(customRedisTemplate.existsKey(refreshTokenKey))) {
이런 부분은 `if (customRedisTemplate.existsKey(refreshTokenKey))` 이렇게 해주셔도 무방합니다. 또는 `BooleanUtils.isTrue(refreshTokenKey))`를 사용하셔도 될거같습니다. 

`Boolean.TRUE.equals` 로 설정하니 가독성이 좋지않네요

2023-04-07 17:39 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +            if (Boolean.TRUE.equals(customRedisTemplate.existsKey(refreshTokenKey))) {
> 이런 부분은 `if (customRedisTemplate.existsKey(refreshTokenKey))` 이렇게 해주셔도 무방합니다. 또는 `BooleanUtils.isTrue(refreshTokenKey))`를 사용하셔도 될거같습니다.
> 
> `Boolean.TRUE.equals` 로 설정하니 가독성이 좋지않네요

이 부부은 인텔리제이에서 자꾸 노란색으로 표시되면서 추천해준걸로 바꾼 내용입니다. ㅜㅜ 다시 기존 방식으로 사용하는게 좋을것같네용

2023-04-07 18:08 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +        if (authorization == null || !CookieUtils.exitsRefreshToken(httpServletRequest.getCookies())) {
> tip. 이런 if 문에 들어가는 부분은 메서드로 분리하면 나중에 이 부분이 어떤걸 검증하는것인지 알기 편합니다.

null 체크 하는 메서드를 만들어 분리하도록 하겠습니다.

2023-04-07 18:36 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +            throw new CustomAuthenticationException(ErrorCode.INVALID_TOKEN);
> 로그아웃을 시도하는데 token값이 잘못되었다면 클라이언트에서 해줄 수 있는게 있을까요? 클라이언트 입장에서는 가지고있는 리프레시토큰을 지우고, 서버에 리프레시토큰 삭제를 요청하고 끝일것으로 보입니다.
> 
> 그러면 서버에서는 리프레시토큰이 있으면 지우고, 없으면 별다른 조치를 하지 않아도 무방할 것으로 보입니다.

사실 이부분은 저도 고민을 했던 부분인데요, 로그아웃 요청은 토큰 값 자체가 잘못되었다고 하더라도 사용자는 별다른 조취를 취할수 없습니다... 악의적인 사용자가 로그아웃처리를 보내거나 변조된 토큰을 요청하거나 서버 입장에선 위험한 토큰임(?) 을 인지하더라도 일단은 해결책이 당장에 토큰을 삭제하는 수밖에 없습니다.(만약 있다면 사용자에게 메일을 주는것?) ㅠㅠ 프론트에서도 로그아웃에서 문제가 있더라도 무조건 accessToken을 브라우저에서 삭제하고 있습니다. 따라서 서버에서 accessToken의 유무만 확인하는것(사실 이것도 확인을 하던 안하던 프론트에서 무조건 삭제처리하는 것은 동일하긴 합니다.) 이 좋을것같습니다. 

또 방금 인지한 사실인데
```
if (!CookieUtils.exitsRefreshToken(httpServletRequest.getCookies())) {
            throw new CustomAuthenticationException(ErrorCode.NON_HEADER_AUTHORIZATION);
        }
```
Set Cookie확인도 설상 쿠키가 없더라도 쿠키는 항상 요청에 포함되기 때문에 이미 쿠키가 만료시간이 되어 자동으로 없어지지 않는 이상 비어있기가 힘듭니다. 따라서 예외시 헤더검증 메세지를 주기보단 이미 삭제된 요청임을 나타내는게 의미상 더 맞는 것같습니다.   (아마도 이 경우는 사용자가 로그인을 시도 한 후 2주동안 한번도 페이지를 건들이지 않다가 2주가 지나서 로그아웃버튼을 처음 클릭한 순간 밖에 없을것같습니다.)

2023-04-07 18:47 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +            throw new CustomAuthenticationException(ErrorCode.INVALID_TOKEN);
> > 로그아웃을 시도하는데 token값이 잘못되었다면 클라이언트에서 해줄 수 있는게 있을까요? 클라이언트 입장에서는 가지고있는 리프레시토큰을 지우고, 서버에 리프레시토큰 삭제를 요청하고 끝일것으로 보입니다.
> > 그러면 서버에서는 리프레시토큰이 있으면 지우고, 없으면 별다른 조치를 하지 않아도 무방할 것으로 보입니다.
> 
> 사실 이부분은 저도 고민을 했던 부분인데요, 로그아웃 요청은 토큰 값 자체가 잘못되었다고 하더라도 사용자는 별다른 조취를 취할수 없습니다... 악의적인 사용자가 로그아웃처리를 보내거나 변조된 토큰을 요청하거나 서버 입장에선 위험한 토큰임(?) 을 인지하더라도 일단은 해결책이 당장에 토큰을 삭제하는 수밖에 없습니다.(만약 있다면 사용자에게 메일을 주는것?) ㅠㅠ 프론트에서도 로그아웃에서 문제가 있더라도 무조건 accessToken을 브라우저에서 삭제하고 있습니다. 따라서 서버에서 accessToken의 문제를 인지하던 안하던 차이는 없습니다. (프론트에서 무조건 삭제처리하는 것은 동일하나 일단은 accessToken에서 유저 정보를 얻어야만 키를 확인할 수 있기 때문에 검증은 해야합니다.) 
> 
> 또 방금 인지한 사실인데
> 
> ```
> if (!CookieUtils.exitsRefreshToken(httpServletRequest.getCookies())) {
>             throw new CustomAuthenticationException(ErrorCode.NON_HEADER_AUTHORIZATION);
>         }
> ```
> 
> Set Cookie확인도 설상 쿠키가 없더라도 쿠키는 항상 요청에 포함되기 때문에 이미 쿠키가 만료시간이 되어 자동으로 없어지지 않는 이상 비어있기가 힘듭니다. 따라서 예외시 헤더검증 메세지를 주기보단 이미 삭제된 요청임을 나타내는게 의미상 더 맞는 것같습니다. (아마도 이 경우는 사용자가 로그인을 시도 한 후 2주동안 한번도 페이지를 건들이지 않다가 2주가 지나서 로그아웃버튼을 처음 클릭한 순간 밖에 없을것같습니다.)

2023-04-09 00:28 UTC, yyy9942 approved these changes
고생하셨습니다. 남겨드린 리뷰는 참고해주시고 머지해주세요~

2023-04-09 00:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/AuthenticationService.java
> +        if (checkingIsNull(authorization) || !CookieUtils.exitsRefreshToken(httpServletRequest.getCookies())) {
null 체크를 한다는 점에서 checking 이라는 동사는 불필요합니다.
`isNotNull(~~)` 과 같은 메서드명이 boolean을 리턴하고 검사를 한다는 관점에서 더 직관적인 메서드 네이밍이 될거에요

2023-04-11 12:55 UTC, merged