프론트 상품 디테일 페이지
E-TF/Fresh-place pull request #48
Opened 2023-04-11 17:53 UTC by suyeonkwong

상품 디테일 페이지를 추가했습니다. 

이렇게 보여집니다!
![detail page](https://user-images.githubusercontent.com/80368511/232544234-816d4c12-3ba7-40d0-8671-79cc41b13639.PNG)

2023-04-14 23:05 UTC, yyy9942 requested changes

2023-04-14 23:05 UTC, yyy9942 commented on src/main/frontend/src/routes/Detail.js
> +
`axios.get(`/public/item/${itemSeq}`)` 이 코드에 대해 서버에서 에러를 내려준다면 어떻게 처리해줄지에 대한 처리가 안되어있는것으로 보입니다.

2023-04-14 23:05 UTC, yyy9942 commented on src/main/frontend/src/routes/Detail.js
> +        if (quantity === 0) {
0과 같다로 비고하기보다는, 명확하게 0보다 작거나 같다 라고 표현해주는게 명확해보입니다.

2023-04-14 23:05 UTC, yyy9942 commented on src/main/frontend/src/routes/Detail.js
> +        setTotalAmount(item.price * quantity)
quantity를 줄여주는 `setQuantity(--quantity);` 부분은 풀어서 쓰면 아래 코드와 같아보입니다.
```
quantity = quantity - 1;
setQuantity(quantity);
```

react에서 상태로 관리하는 `quantity`와 같은 상태는 값을 재할당하면 절대 안됩니다. 모든 값의 변경은 `useState`를 통해 얻은 `setXxx`형식의 함수를 통해 이루어져야 합니다.

그러면 `setTotalAmount`는 어떻게 처리하면 될까요?
`react`에는 특정 상태가 변경되면 그 이벤트를 받아 처리하는 `useEffect`가 있습니다. 
` setTotalAmount(item.price * quantity)` 를 `useEffect`를 통해 처리하면 `quantity`가 변경될 때 자동으로 연동되어 처리되도록 변경할 수 있겠네요.

2023-04-14 23:05 UTC, yyy9942 commented on src/main/frontend/src/routes/Detail.js
> +    let [totalAmount, setTotalAmount] = useState(0);
react 사용시 상태(`useState`)를 사용한다면 let이 아닌 const명령어를 통해 상수처럼 사용해주세요. 해당 상태는 값의 변경이나 값의 재할당이 일어나면 안됩니다.

2023-04-14 23:06 UTC, yyy9942 commented
추가적으로 PR 내용이 비어있습니다. 이 부분 채워주세요~

2023-04-17 15:06 UTC, suyeonkwong commented on src/main/frontend/src/routes/Detail.js
> +    let [totalAmount, setTotalAmount] = useState(0);
> react 사용시 상태(`useState`)를 사용한다면 let이 아닌 const명령어를 통해 상수처럼 사용해주세요. 해당 상태는 값의 변경이나 값의 재할당이 일어나면 안됩니다.

재할당이 일어나지 않게 const로 변경하도록 하겠습니다.

2023-04-17 15:14 UTC, suyeonkwong commented on src/main/frontend/src/routes/Detail.js
> +        setTotalAmount(item.price * quantity)
> react에서 상태로 관리하는 `quantity`와 같은 상태는 값을 재할당하면 절대 안됩니다. 모든 값의 변경은 `useState`를 통해 얻은 `setXxx`형식의 함수를 통해 이루어져야 합니다.
>
set으로만 useState의 상태를 변경하도록 주의하겠습니다.!

> 그러면 `setTotalAmount`는 어떻게 처리하면 될까요? `react`에는 특정 상태가 변경되면 그 이벤트를 받아 처리하는 `useEffect`가 있습니다. ` setTotalAmount(item.price * quantity)` 를 `useEffect`를 통해 처리하면 `quantity`가 변경될 때 자동으로 연동되어 처리되도록 변경할 수 있겠네요.
>
useEffect를 사용해서 자동으로 total값을 처리하도록 하겠습니다.!

2023-04-17 15:26 UTC, suyeonkwong commented on src/main/frontend/src/routes/Detail.js
> +
> `axios.get(`/public/item/${itemSeq}`)` 이 코드에 대해 서버에서 에러를 내려준다면 어떻게 처리해줄지에 대한 처리가 안되어있는것으로 보입니다.

error에 따라서 상품이 준비되지 않거나 일시적인 장애가 생겼다는 것을 alert를 띄우는것이 좋을것같습니다.

2023-04-20 10:31 UTC, yyy9942 approved these changes
확인하였습니다. 머지해주세요~

2023-04-20 14:00 UTC, merged