프론트 장바구니 페이지
E-TF/Fresh-place pull request #49
Opened 2023-04-13 17:32 UTC by suyeonkwong

장바구니 다음 기능은 현재 페이지에서 로그인 인증 정보에 따라 배송지 입력 컴포넌트 생기게하고 주문하기 컴포넌트를 생성해보도록 하겠습니다.

2023-04-14 23:17 UTC, yyy9942 requested changes

2023-04-14 23:17 UTC, yyy9942 commented on src/main/frontend/src/routes/Cart.js
> +}
`target`이 `null`일 경우 undefined를 리턴할 것으로 보이는데, 이 부분에 대한 처리가 필요해보입니다.
명시적으로 예외를 던지거나 별도 에러 핸들링을 해주세요

2023-04-14 23:17 UTC, yyy9942 commented on src/main/frontend/src/store/cartItemSlice.js
> +            num === -1 ? state.push(action.payload) : state[num].quantity += action.payload.quantity;
변수 선언시 특별한 사유가 없다면 모두 상수로 선언해주세요. 상수로 선언하는것만으로도 발생할 수 있는 휴먼 에러를 많이 방지할 수 있습니다.

2023-04-17 18:09 UTC, suyeonkwong commented on src/main/frontend/src/routes/Cart.js
> +}
> `target`이 `null`일 경우 undefined를 리턴할 것으로 보이는데, 이 부분에 대한 처리가 필요해보입니다. 명시적으로 예외를 던지거나 별도 에러 핸들링을 해주세요

사용하는 쪽에서 '&&' 로 null 체크를 해주는것이 좋을것같습니당

2023-04-17 18:09 UTC, suyeonkwong commented on src/main/frontend/src/store/cartItemSlice.js
> +            num === -1 ? state.push(action.payload) : state[num].quantity += action.payload.quantity;
> 변수 선언시 특별한 사유가 없다면 모두 상수로 선언해주세요. 상수로 선언하는것만으로도 발생할 수 있는 휴먼 에러를 많이 방지할 수 있습니다.

변경 가능성이 없다면 상수로 선언하도록 주의하겠습니다!

2023-04-20 23:00 UTC, yyy9942 commented on src/main/frontend/src/routes/Cart.js
> +}
그러면 이 함수를 사용하는곳에서는 &&를 무조건 사용해야만 하는거고,
추가적으로 이 함수는 undefined 또는 number타입을 리턴하는 다중 타입 함수가 되어서 관리측면에서 어렵지 않을까요?

2023-04-20 23:12 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +                <Route path="/public/cart" element={<Cart navigate={navigate}/>}/>
지금 props로 navigate를 넘기고있는데 그 이유가 있을까요?
필요한경우 props로 받아오지 않더라도 해당 컴포넌트 내부에서 `useNavigate()`를 사용하면 `navigate`를 props로 받아오지 않아도 됩니다.

2023-04-20 23:12 UTC, yyy9942 commented on src/main/frontend/src/routes/Cart.js
> +function Cart(props) {
이렇게만 선언해두면 props 내부에 어떤게 있는지 알기 어렵습니다. 
[객체 구조 분해 할당](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%ED%95%A8%EC%88%98_%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EB%A1%9C_%EC%A0%84%EB%8B%AC%EB%90%9C_%EA%B0%9D%EC%B2%B4%EC%97%90%EC%84%9C_%ED%95%84%EB%93%9C_%ED%95%B4%EC%B2%B4%ED%95%98%EA%B8%B0)이라는 기능을 사용하면 이런 단점을 조금 상쇄할 수 있습니다.

정확하게 사용할 변수에 대해서만 선언하는것도 가능하니 props선언시 참고해주세요.

2023-04-20 23:12 UTC, yyy9942 commented on src/main/frontend/src/routes/Cart.js
> +                            <Button variant="info" onClick={() => props.navigate('/')}>쇼핑하러 가기</Button>
`navigate`를 props로 전달받을 이유가 없어보입니다.
별도 이유가 있다면 말씀해주시고, 아니라면 React hook인 `useNavigate`를 사용해주세요.

2023-04-21 07:03 UTC, suyeonkwong commented on src/main/frontend/src/routes/Cart.js
> +function Cart(props) {
> 이렇게만 선언해두면 props 내부에 어떤게 있는지 알기 어렵습니다. [객체 구조 분해 할당](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%ED%95%A8%EC%88%98_%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EB%A1%9C_%EC%A0%84%EB%8B%AC%EB%90%9C_%EA%B0%9D%EC%B2%B4%EC%97%90%EC%84%9C_%ED%95%84%EB%93%9C_%ED%95%B4%EC%B2%B4%ED%95%98%EA%B8%B0)이라는 기능을 사용하면 이런 단점을 조금 상쇄할 수 있습니다.
> 
> 정확하게 사용할 변수에 대해서만 선언하는것도 가능하니 props선언시 참고해주세요.

```
const CartItem = ({item, dispatch})
```
이렇게 사용하니까 훨씬 가독성도 좋아졌어요!

2023-04-21 07:07 UTC, suyeonkwong commented on src/main/frontend/src/App.js
> +                <Route path="/public/cart" element={<Cart navigate={navigate}/>}/>
> 지금 props로 navigate를 넘기고있는데 그 이유가 있을까요? 필요한경우 props로 받아오지 않더라도 해당 컴포넌트 내부에서 `useNavigate()`를 사용하면 `navigate`를 props로 받아오지 않아도 됩니다.

같은 Hook을 재선언하지 않는게(한페이지로 돌아가는거니까 최대한 줄이는게 좋을것이라고 판단) 메모리를 아낄수 있다고 생각해서 호출하는 쪽에서 전달했습니다. ㅠㅠ 관련이 없다면 컴포넌트에서 새롭게 선언하도록 하겠습니다.

2023-04-21 07:10 UTC, suyeonkwong commented on src/main/frontend/src/routes/Cart.js
> +                            <Button variant="info" onClick={() => props.navigate('/')}>쇼핑하러 가기</Button>
> `navigate`를 props로 전달받을 이유가 없어보입니다. 별도 이유가 있다면 말씀해주시고, 아니라면 React hook인 `useNavigate`를 사용해주세요.

이유는 위에서 설명한것처럼 최대한 재선언?을 하지 않도록 하기 위해서였습니다. 이부분은 수정하도록 하겠습니다!

2023-04-21 14:50 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +                <Route path="/public/cart" element={<Cart navigate={navigate}/>}/>
Hook을 사용한다고 메모리를 아낄 수 있다고 생각하는 근거가 있으실까요? 만약 아낀다고 하면 어느정도로 아낄 수 있고, 이로인해 얻을 수 있는 이점은 어떤게 있을까요?

2023-04-21 19:52 UTC, suyeonkwong commented on src/main/frontend/src/App.js
> +                <Route path="/public/cart" element={<Cart navigate={navigate}/>}/>
> Hook을 사용한다고 메모리를 아낄 수 있다고 생각하는 근거가 있으실까요? 만약 아낀다고 하면 어느정도로 아낄 수 있고, 이로인해 얻을 수 있는 이점은 어떤게 있을까요?

아뇨! 제가 말한건 'Hook을 사용하면 무조건 메모리를 아낄 수 있다'가 아니라 '같은 useNavigate를 호출하는 쪽과 호출 받는 쪽에서 두번 호출하는게 효율이 떨어질것같다'고 생각했다는 의견입니당. 대신 저렇게 props 넘겨받으면 컴포넌트 내부의 Hook이 최상위에서만 실행되어야 한다는 규칙이 깨지는게 문제가 될수도 있다는 생각이 듭니다.

2023-04-21 20:16 UTC, suyeonkwong commented on src/main/frontend/src/routes/Cart.js
> +}
> 그러면 이 함수를 사용하는곳에서는 &&를 무조건 사용해야만 하는거고, 추가적으로 이 함수는 undefined 또는 number타입을 리턴하는 다중 타입 함수가 되어서 관리측면에서 어렵지 않을까요?

그럼 타입체크를 해주는것도 좋은 방법일것같습니다!

2023-04-23 06:33 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +        Logout(navigate)
이부분이 아직 navigate를 넘기는것으로 보입니다

2023-04-24 14:54 UTC, suyeonkwong commented on src/main/frontend/src/App.js
> +        Logout(navigate)
> 이부분이 아직 navigate를 넘기는것으로 보입니다

useNavigate를 Logout()에서 사용하면 App.js에서 호출할 때 'Only Call Hooks from React Functions;' 법칙에 어긋나서 Invalid Hooks 에러가 납니다

2023-04-25 22:32 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +        Logout(navigate)
동일한 파일에 있는 Login 의 경우 Hook을 사용하는데에도 불구하고 에러를 주지 않을것으로 보입니다. 어떤 차이가 있는걸까요?

2023-04-25 22:33 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +                <Route path="/public/cart" element={<Cart navigate={navigate}/>}/>
컴포넌트에서 hook이 최상위에서만 실행되어야한다는 규칙이 있나요? 그러면 Root에서만 hook을 사용해야하는것 아닌가요?

2023-04-29 02:26 UTC, yyy9942 approved these changes
고생하셨습니다. 머지해도좋습니다

2023-04-29 02:26 UTC, yyy9942 commented on src/main/frontend/src/App.js
> +                <Route path="/members/logout" element={<Logout/>}/>
👍  이제 다른곳에서도 로그아웃을 URL만으로도 할 수 있겠네요

2023-04-29 02:26 UTC, yyy9942 commented on src/main/frontend/src/routes/Detail.js
> +        if (quantity <= 1) {
1일때 아무 동작을하지 않는다면, 0개는 고를 수 없도록해둔건가요?

2023-04-29 07:22 UTC, suyeonkwong commented on src/main/frontend/src/routes/Detail.js
> +        if (quantity <= 1) {
> 1일때 아무 동작을하지 않는다면, 0개는 고를 수 없도록해둔건가요?

넵. 0까지 고르면 디테일에서 totalAmount가 0원이 되므로 어색해서 변경했습니다.

2023-04-29 15:51 UTC, merged