API URL 구분하기
E-TF/Fresh-place pull request #52
Opened 2023-04-20 19:53 UTC by suyeonkwong

2023-04-20 23:26 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/ViewController.java
> +    }
에러를 통해서 index를 내려주는 방식은 flow상 어색합니다.

비즈니스로직으로 index.html을 내려주는 컨트롤러를 만들고, 필터에서 해당 컨트롤러를 탈 수 있도록 변경해주셔야 하며 에러 URL에서는 명시적으로 에러 핸들링 또는 에러 페이지를 내려주도록 해주세요,.

2023-04-21 20:25 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/ViewController.java
> +    }
> 비즈니스로직으로 index.html을 내려주는 컨트롤러를 만들고, 필터에서 해당 컨트롤러를 탈 수 있도록 변경해주셔야 하며 에러 URL에서는 명시적으로 에러 핸들링 또는 에러 페이지를 내려주도록 해주세요,.

필터에서 컨트롤러를 타게 할때 궁금한게 있었는데요 url 패턴을 not으로 시작하게 조절하는 방법이 있을까요?ㅜㅜ 그게 아니라면 현재 토큰 검증하는 필터를 거치면 핸들러 매핑 되기전에 리턴되는 문제가 있어서 너무 많은 패턴을 적어줘야 해서요 ㅜㅜ 검색했는데 일치하지 않는 패턴과 관련된 정보를 찾지 못했습니다. ㅜㅜ

2023-04-25 22:28 UTC, yyy9942 requested changes

2023-04-25 22:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +                    .anyRequest().authenticated()
👍

2023-04-25 22:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +    static class ViewSecurityConfig extends WebSecurityConfigurerAdapter {
SecurityConfig를 왜 2개로 두신건가요? 1개의 설정으로는 구현이 불가했었나요?

2023-04-25 22:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +                    .addFilterBefore(new ViewFilter(), UsernamePasswordAuthenticationFilter.class);
이 설정을 기존 설정에 붙이기만 하면 설정파일 2개를 사용하지 않아도 되지 않을까요?

2023-04-25 22:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/ViewController.java
> +    @RequestMapping("/index")
👍

2023-04-25 22:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/filter/ViewFilter.java
> +        }
URI가 `/api/{}/{}` 형식일때는 잘 동작할것으로 보입니다.
그렇다면 만약 `/apixxxxxx`로 들어온다면 예상한대로 동작할까요?

2023-04-26 05:20 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/filter/ViewFilter.java
> +        }
> URI가 `/api/{}/{}` 형식일때는 잘 동작할것으로 보입니다. 그렇다면 만약 `/apixxxxxx`로 들어온다면 예상한대로 동작할까요?

아뇨! '/api/' 로 변경하겠습니다.

2023-04-26 06:11 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +                    .addFilterBefore(new ViewFilter(), UsernamePasswordAuthenticationFilter.class);
> 이 설정을 기존 설정에 붙이기만 하면 설정파일 2개를 사용하지 않아도 되지 않을까요?

옙. 굳이 두개로 설정 안해도 하나의 시큐리티 필터에서 필터 체인으로 필터를 등록하면 됩니당. 설정이 모두 겹치므로 하나로 변경하겠습니다.

2023-04-29 02:28 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/ViewController.java
> +    }
not을 사용하지 않고도 할 수 있는방법이 많죠. 이번 수정에서 그걸 잘 적용한걸로 보이네요

2023-04-29 02:28 UTC, yyy9942 approved these changes
확인하였습니다. 머지하셔도 좋습니다.

2023-04-29 06:53 UTC, merged