Facade Pattern 구조
E-TF/Fresh-place pull request #6
Opened 2022-07-22 12:20 UTC by suyeonkwong

기존 코드는 Service에서 여러 Service와 Repository에 대한 의존때문에 책임이 명확하지 않고 응집도가 낮은 클래스라고 판단하였습니다.  그래서 Service 와 repository를 1대 1 로 의존해서 책임을 명확하게 하고 , 표현 계층에 domain노출하지 않기 등을 위해 조합만을 책임지는 Facade클래스를 만들어 전체 구조를 변경했습니다!

기존의 MemberController 를 AccountController와 ProfileController로 구분하였고, 기존에 있던 MemberService가 수행하던 회원가입, 프로필 관리, 등급 조회 등을 각각의 Service로 분리하였고, 1개의 Service가 1개의 dao에 의존하도록 했습니다.  그리고 실제 기능에 필요한 각각의 Service를 조합하여 수행하는 Facade 클래스를 따로 생성했습니다. 

새롭게 추가된 기능은 배송지 조회, 생성, 수정 입니다. 한 브랜치에 너무 많은 기능을 만들지 않도록 했는데 전체 구조가 변경되어버려서.. 이부분은 다음 부터는 제대로 분리하도록 하겠습니다. 

배송지를 수정하는 dto가 너무 여러개라서 innerClass로 관리했습니다.

2022-07-23 07:55 UTC, yyy9942 requested changes
퍼사드 패턴의 적용 자체는 괜찮은 시도로 보입니다 :) 👍

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/SignupFacade.java
> +public class SignupFacade {
퍼사드 패턴의 네이밍컨벤션은 F~~~입니다.
ex) `FSignupService`
퍼사드 계층의 서비스또한 서비스 레이어기 때문에 뒤쪽에 suffix로 Service를 붙여주면 좋을거같아요.

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/SignupFacade.java
> +    public void signupInner(final SignupRequest signupRequest) {
이거는 private로 해야 하지 않을까요?
중복 low를 막기 위해 Lock적용을 한 `signup`만 public으로 오픈하고 이부분은 private로 감춰두어야 다른곳에서 이 메서드를 직접적으로 호출하는것을 막을 수 있습니다.

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/ErrorResponse.java
> +    public static ResponseEntity<ErrorResponse> errorResponseAndValue(ErrorCode errorCode, Object value) {
value의 경우 메세지에 출력하는 용도로 사용하는거라 Object 타입일 이유가 없어보입니다. String타입으로 다시 롤백하고 필요한경우 해당 객체의 toString을 호출하여 매개변수로 넘겨주는것이 더 깔끔할 것으로 보입니다.

Object를 직접 이렇게 넘긴 후 메서드 내부에서 toString을 호출한다면 의도하지 않은(오버라이딩하지 않은) toString이 호출되고, 그러면 메세지를 봐도 이게 어떤 데이터를 가진 객체인지 알 수 없겠죠?

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/exception/WrongValueException.java
> +    private final Object value;
Object타입 사용은 지양해주시고, 통상적인 unknown 타입이 필요하다면 제네릭을 사용해주세요~

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/repository/DeliveryAddressRepository.java
> +    List<DeliverAddress> findAllByMember(Member member);
이전 PR내용을 참고해주세요 :)
엔티티를 직접 매개변수로 사용하지 말고 id를 통해 조회해오도록 변경해주세요

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/DeliveryAddressFacade.java
> +        DeliverAddress deliverAddress = isMemberCheck(memberId, zipCode.getDeliverSeq());
메서드 네이밍 `isMemberCheck`은 어떤걸 체크하는지 명시적이지 않아보입니다.
명시적인 이름으로 변경해주세요~

2022-07-23 07:55 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/DiscountByGradeService.java
> +    }
트랜잭션이 안걸려있는걸로 보입니다

2022-07-23 09:59 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/DiscountByGradeService.java
> +    }
> 트랜잭션이 안걸려있는걸로 보입니다

ㅠㅠ 실수했습니다..

2022-07-23 10:19 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/DeliveryAddressFacade.java
> +        DeliverAddress deliverAddress = isMemberCheck(memberId, zipCode.getDeliverSeq());
> 메서드 네이밍 `isMemberCheck`은 어떤걸 체크하는지 명시적이지 않아보입니다. 명시적인 이름으로 변경해주세요~

isMemberIdCheck가 조금 더 구체적일까요??

2022-07-23 12:07 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/SignupFacade.java
> +public class SignupFacade {
> 퍼사드 패턴의 네이밍컨벤션은 F~~~입니다. ex) `FSignupService` 퍼사드 계층의 서비스또한 서비스 레이어기 때문에 뒤쪽에 suffix로 Service를 붙여주면 좋을거같아요.

네 ㅎㅎ Facade클래스 네이밍을 변경하도록 하겠습니다

2022-07-23 12:44 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/DeliveryAddressFacade.java
> +        DeliverAddress deliverAddress = isMemberCheck(memberId, zipCode.getDeliverSeq());
>getDeliveryAddressAfterCheckingAuthorityByMember() 이게 좋을것같습니다!

2022-07-23 12:47 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/SignupFacade.java
> +    public void signupInner(final SignupRequest signupRequest) {
> 이거는 private로 해야 하지 않을까요? 중복 low를 막기 위해 Lock적용을 한 `signup`만 public으로 오픈하고 이부분은 private로 감춰두어야 다른곳에서 이 메서드를 직접적으로 호출하는것을 막을 수 있습니다.

@Transaction이 걸려 있으면 private을 사용할수가 없고.. 또 이부분 테스트 작성할때 lock을 잡지 않았을 경우를 대비해서 signupInner를 직접 호출하는 부분이 있습니다.

2022-07-24 00:19 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/DeliveryAddressFacade.java
> +        DeliverAddress deliverAddress = isMemberCheck(memberId, zipCode.getDeliverSeq());
저 메서드의 목적을 보니 deliverSeq과 memberId가 매칭되는지 확인하는듯하네요.
`get~~` 의 경우 리턴타입이 object인 경우 사용합니다. boolean 타입의 리턴을 가지는 메서드는 `is~~~` 네이밍을 가지는게 직관적입니다.
`isMemberDeliveryAddressMatch` 같은 형식도 괜찮을 것이고 여러 형식의 메서드이름을 정해보세요.

2022-07-24 00:20 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/SignupFacade.java
> +    public void signupInner(final SignupRequest signupRequest) {
그렇다면 해당 메서드는 최소한 동일한 패키지에서만 실행할 수 있도록 default 또는 protected레벨의 오픈을 고려해도 좋을거같네요~

2022-07-28 13:25 UTC, yyy9942 requested changes
아래 리뷰 확인해주세요~

2022-07-28 13:25 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/CacheConfig.java
> +    }
캐시매니저에서 사용할 캐시들을 세팅하실 때 이렇게 세팅하시면 이게 곧 하드코딩이 될 수 있습니다.
```
simpleCacheManager.setCaches(List.of(new ConcurrentMapCache("grade")));
```
위의 코드에서 `List.of(new ConcurrentMapCache("grade"))`부분은 코드 안에 리터럴형태로 넣으면 추후 어떤 캐시가 관리되고있는지 확인하기 어려울 수 있습니다. 별도 상수로 관리를 해주시는게 좋습니다 :)

2022-07-28 13:25 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/DiscountByGradeService.java
> +        log.info("grade 캐시가 없는 경우");
요런 로그는 의미가 없다고 볼 수 있습니다. 제거하시거나 의미있는 로그를 남겨주세요~
나중에 이런 로그들이 더미로 쌓이게되면 실제 필요한 로그를 확인하기 어려워질 수도 있습니다.

2022-07-29 11:25 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/CacheConfig.java
> +    }
> 캐시매니저에서 사용할 캐시들을 세팅하실 때 이렇게 세팅하시면 이게 곧 하드코딩이 될 수 있습니다.
> 
> ```
> simpleCacheManager.setCaches(List.of(new ConcurrentMapCache("grade")));
> ```
> 
> 위의 코드에서 `List.of(new ConcurrentMapCache("grade"))`부분은 코드 안에 리터럴형태로 넣으면 추후 어떤 캐시가 관리되고있는지 확인하기 어려울 수 있습니다. 별도 상수로 관리를 해주시는게 좋습니다 :)

네!! 상수로 관리하겠습니다.

2022-07-29 11:27 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/DiscountByGradeService.java
> +        log.info("grade 캐시가 없는 경우");
> 요런 로그는 의미가 없다고 볼 수 있습니다. 제거하시거나 의미있는 로그를 남겨주세요~ 나중에 이런 로그들이 더미로 쌓이게되면 실제 필요한 로그를 확인하기 어려워질 수도 있습니다.

네~ 로그는 주의해서 사용하겠습니다!!

2022-07-29 14:16 UTC, yyy9942 approved these changes
고생하셨습니다~ 머지하셔도 좋습니다 :)

2022-07-30 07:18 UTC, merged