상품조회와 이미지 업로드
E-TF/Fresh-place pull request #7
Opened 2022-08-31 05:09 UTC by suyeonkwong

상품(Item) 의 카테고리 테이블을 따로 생성하지 않았기 때문에 아이템의 카테고리 코드 컬럼에 공통코드 테이블의 코드값이 들어가있습니다. 

그런데 카테고리 서비스를 사용하기 위해서는 (단순 카테고리 조회, 카테고리 타입을 통한 상품리스트 조회 등등) 공통코드 테이블의 코드값을 가지고 그룹코드와 코드명등을 조회해야 하는데 생각해보니 

카테고리 같은 경우 변경작업이 잘 일어나지 않는데도 아이템 조회 할때마다 코드 테이블에 접근해야 한다는 점이 불편해서 카테고리 자체를 enum으로 관리했습니다.

그리고 컨버터를 통해서 컬럼과 엔티티를 각 속성에 맞게 변경시켰습니다. 

공통코드테이블에 카테고리 코드 외에도 등급코드나 주문상태코드, 결제방법코드, 결제상태코드 등이 있는데 사실 이 코드들을 enum으로 관리하면 굳이 공통코드 테이블이 필요할까? 라는 생각을 했습니다. 그래서 차라리 코드 테이블을 삭제 하고싶은데 공통코드 테이블을 반드시 가지고 있어야 할까요?

다음은 상품 이미지에 대한 내용인데 이미지 업로드 할때 url을 
[ / image / {type} / {itemSeq} || {reviewSeq} / uuid_파일명 / 파일 이름 ] 으로 생성 하여  이미지테이블에서 관리했고 
저장소는 S3를 선택하여 사진을 최초 업로드 할때 썸네일을 생성하여 같이 저장하는 방식을 선택했습니다 ^^

2022-09-03 03:12 UTC, yyy9942 commented
리뷰 전 질문에 대한 답변먼저 드리겠습니다.

Q. 공통코드테이블에 카테고리 코드 외에도 등급코드나 주문상태코드, 결제방법코드, 결제상태코드 등이 있는데 사실 이 코드들을 enum으로 관리하면 굳이 공통코드 테이블이 필요할까? 라는 생각을 했습니다. 그래서 차라리 코드 테이블을 삭제 하고싶은데 공통코드 테이블을 반드시 가지고 있어야 할까요?

A. 공통코드로 관리하는 것과 Enum으로 관리하는것 두가지 모두 장단점이 있습니다. 실시간 서버에 배포 없이 카테고리를 추가하고싶다면 enum으로 관리해서는 실시간 추가/삭제 변경이 어려운반면 공통코드로 관리한다면 해당 DB의 값만 바꾸면되니 변경에 유연할 수 있습니다. enum으로 관리한다면 DB조회를 하지 않아도 되고, IO횟수가 줄어드는 장점이 있을 수 있겠네요.

여러가지 장단점을 비교해서 어떻게 구현하실지 고민해보시면 좋을거같습니다.

2022-09-03 04:12 UTC, yyy9942 requested changes
변경이 거의 없는데이터에 캐시를 적용한시도는 꽤 괜찮아보입니다. 다만 캐시를 적용할 때 고려할점이 있는데요,
1. 데이터가 변경되었을 때 캐시를 어떻게 초기화해줄것인지
2. 서버가 여러대 올라간 상태에서 현재 사용하는것처럼 로컬캐시를 적용했을 때 어떤 서버는 변경된데이터를, 어떤 서버는 캐시되어 변경되기 전 데이터를 보여줄 수 있을텐데 이부분은 어떻게 해결할 수 있을지
3. 캐시의 유효기간은 어떻게 설정할것인지

위와같은 부분에 대한 고려가 되어야합니다. 이부분에 대해서 어떻게 구현하실지 고민해본 후 답변부탁드려요~

---

이미지 리사이징을 진행하면 이미지 파일 크기가 어느정도로 줄어들었나요?

2022-09-03 04:12 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/FImageUploadService.java
> +    public void saveItemImage(final Long id, final MultipartFile multipartFile) {
그리고 MultipartFile로 받아와 저장하는것에 성공하셨네요 ㅎㅎ 고생하셨습니다

2022-09-03 04:12 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/S3Service.java
> +    }
concat 체이닝보다 + 연산이 더 가독성있지 않을까요?
```suggestion
    private String createFilePath(String directoryName, Long objectName, String fileName) {
        return directoryName + "/" + objectName.toString() + UUID.randomUUID() + fileName;
    }
```

2022-09-03 04:12 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/constant/Category.java
> +    MEA_CAT( "육류", Arrays.asList(CategoryType.BEE_MEA, CategoryType.POR_MEA, CategoryType.LAM_MEA, CategoryType.CHI_MEA, CategoryType.DUC_MEA, CategoryType.EGG_MEA)),
```suggestion
    MEA_CAT("육류", Arrays.asList(CategoryType.BEE_MEA, CategoryType.POR_MEA, CategoryType.LAM_MEA, CategoryType.CHI_MEA, CategoryType.DUC_MEA, CategoryType.EGG_MEA)),
```

2022-09-05 10:03 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/SecurityConfig.java
> +                .mvcMatchers(HttpMethod.DELETE, "/delete/**").permitAll()
> 1. 이미지 업로드와 delete를 권한없는 대상이 하는 경우가 있을까요?
> 2. prefix로 인증없이 접근할 수 있는 URL을 `/pulblic/**` 형식으로 만든다면 API 생성때마다 권한처리를 해주지 않아도 될거같네요. 이미 회원가입의경우 /public으로 시작하는 URL 네이밍 컨밴션이 있으니 이런 컨밴션을 통일하면 좋을거같습니다.

이미지 업로드는 상품이미지 업로드와 리뷰 작성 시 업로드 되는데 이미지 업로드 해주는 권한을 추가해야 할것같습니다.

2022-09-05 12:30 UTC, suyeonkwong commented on src/main/java/individual/freshplace/repository/ItemRepository.java
> +}
> 페이징에 대한 고려도 있어야할거같습니다. 상품이 카테고리별로 엄청나게 많다고 하면 이 쿼리 한번으로 너무나 많은 데이터를 들고올수도 있으니까요.

페이징에 대한 처리를 고려하도록 하겠습니다!

2022-09-20 17:57 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/ItemController.java
> +    }
> 이부분은 `/items...`하위 URL이지만 item과는 관련이 크게 없는 URL로 보입니다. 이미지에 item을 받는것도 아니고 단순히 이미지 업로드를 해주는걸로 보여요. 이런 단순 업로드의 경우 `/items...`하위 URL이 아닌 독자적인 이미지 업로드 URL로 만들어주시는게 좋을거같네요

단순 업로드이기 때문에 ItemController가 아닌 ImageController를 생성하는것이 좋을것같습니다.!

2022-09-21 02:59 UTC, suyeonkwong commented
> 이미지 리사이징을 진행하면 이미지 파일 크기가 어느정도로 줄어들었나요?

원본 이미지 크기와 포맷에 따라 다르지만 jpg 파일같은 경우 평균적으로 67.2% 의 크기가 감소하였고 가로폭에 대해 차이가 클 경우 최대 89% 까지 크키가 줄었습니다!

2022-09-21 11:25 UTC, suyeonkwong commented
> A. 공통코드로 관리하는 것과 Enum으로 관리하는것 두가지 모두 장단점이 있습니다. 실시간 서버에 배포 없이 카테고리를 추가하고싶다면 enum으로 관리해서는 실시간 추가/삭제 변경이 어려운반면 공통코드로 관리한다면 해당 DB의 값만 바꾸면되니 변경에 유연할 수 있습니다. enum으로 관리한다면 DB조회를 하지 않아도 되고, IO횟수가 줄어드는 장점이 있을 수 있겠네요.
> 
> 여러가지 장단점을 비교해서 어떻게 구현하실지 고민해보시면 좋을거같습니다.

코트 테이블을 삭제하고 enum으로 관리하는 방법을 선택했습니다. 그런데 enum 사용시 문제가 될 수 있는 부분이 카테고리 코드같은 경우 캐시데이터에 포함되는 경우가 있는데 만약 인스턴스 자체에 변경사항이 생긴다면 캐시 변경사항을 어떻게 적용해줘야 할지 고민을 많이 했습니다. 물론 카테고리같은 경우 변경사항이 거의 드물지만 만약 변경사항이 있을 경우를 대비해 유효시간을 원래 생각했던 시간보다 짧게 지정하는 방법을 선택했습니다. ^^

2022-09-23 01:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/auth/PrincipalDetails.java
> +        return authorities;
이런 컬랙션들도 불변함을 유지하기 위해선 불변컬랙션을 사용해주시는게 좋습니다.
```
List.of(new SimpleGrantedAuthority(role))
```
이렇게 쓰시면 됩니다.

2022-09-23 01:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/ImageController.java
> +    }
이미지 업로드 이후 이미지의 링크 또는 이미지 업로드된 경로를 어떻게 알아올 수 있을까요?
업로드 이후 200 OK 값만 내려주는듯하여 질문드립니다

2022-09-23 01:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/deliveryaddress/DeliveryAddressResponse.java
> +    private final Long deliverSeq;
Response인데 래퍼타입인 Long을 쓸 이유가 있을까요? `deliverSeq`가 null인 경우가 없다면 primitive 타입을 쓰는게 좋을듯합니다.

2022-09-23 14:17 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/ImageController.java
> +    }
> 이미지 업로드 이후 이미지의 링크 또는 이미지 업로드된 경로를 어떻게 알아올 수 있을까요? 업로드 이후 200 OK 값만 내려주는듯하여 질문드립니다

db에 저장되는 값이라서 내려줄 생각을 안했는데 return해주는게 좋을것같습니다

2022-10-02 00:31 UTC, yyy9942 approved these changes
고생하셨습니다 머지하셔도 좋습니다

2022-10-08 08:09 UTC, merged