장바구니와 쿠키
E-TF/Fresh-place pull request #8
Opened 2022-10-16 13:33 UTC by suyeonkwong

안녕하세요. 회원과 비회원 장바구니 기능을 쿠키로 구현하려고 합니다. 제가 생각한 부분에 대해 문제가 될 수 있는 부분을 알려주시면 감사하겠습니다. 

장바구니 테이블을 사용하지 않고 단순 쿠키만 사용하였는데 이유는 다음과 같습니다. 

1. 장바구니에서 구매하기를 선택하면 장바구니에 담은 상품 삭제해야함.
2. 만약 구매를 안하더라도 장바구니에서 (예를 들어 3일 정도 주기로) 삭제해야함. 
3. 서비스를 이용할때만 잠깐 사용하고싶고 db쓰기 싫음.
4. 만약 회원의 관심 상품같은 부가적인 정보가 필요할 때 주문 태이블로도 충분할것같음.
5. 로그인 처리를 토큰으로 하고 있는데(세션 사용 안함 X) 쿠키는 stateless 하게 잠깐 사용하고 버릴 수 있어서 간편함.
6. 쿠키 보안 때문에 고민을 했지만 쿠키에 상품이름, 가격, 수량 정도의 정보밖에 안담겨있음. (개인정보 하나도 없음)
7. 쿠키 크기도 문제가 될 수 있지만(호스트당 20개, 브라우저마다 다르지만 대부분 4000바이트 이상, 1글자에 2바이트니까 2000글자) 단순히 장바구니 기능으로 볼때 쿠키 최대 갯수가 20개 이상이 될 확률이 적음.
8. 요청마다 쿠키를 전송해야하는 단점이 있지만 최대 4KB 이므로 이정도는 감수해도 된다고 생각함.

제가 생각한 이유는 이정도입니다. 만약 이런식으로 구현한다면 어떤 문제점이 발생할 수 있을까요? 일단 쿠키 도메인과 경로는 모두 열어두었습니다.

2022-10-23 01:33 UTC, yyy9942 requested changes

2022-10-23 01:33 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +    static final String COOKIE_EMPTY_STRING = "장바구니가 비어있습니다.";
1. 다른곳에서도 사용할 수 있는 상수는 컨트롤러에 선언하는것이 적절하지 않습니다. 서비스나 다른 유틸레벨에서 재사용하기 위해서는  별도의 상수 클래스로 빼두시는게 좋습니다.
2. 접근제어자가 빠져있습니다.

2022-10-23 01:33 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +        else {
else문 쓰지않는것을 목표로 해보세요. else문을 쓰는 순간 코드 가독성이 많이 떨어집니다.
자세한 내용은 요거 참고해주세요
https://stackoverflow.com/questions/9191388/it-is-more-efficient-to-use-if-return-return-or-if-else-return

2022-10-23 01:33 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +        }
중복되는 로직은 메서드로 분리해주세요

2022-10-23 01:33 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +    }
컨트롤러 레벨에서 비즈니스 로직을 수행할 때에는
1. 메서드로 해당 기능을 분리하거나
2. 베스트는 Util / Service로 해당 로직을 분리해야합니다
컨트롤러는 비즈니스로직을 처리하기 부적절한 레이어에요. 이런 로직은 재사용하거나 관심사를 모을 수 있게 별도의 클래스로 빼주시는걸 고려해주세요.

EX) Cookie Utils로 빼거나.. ItemService에 추가하거나

2022-10-23 01:33 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +        cookie.setMaxAge(3600 * 12);
비즈니스 로직에 숫자가 그대로 들어있는걸 매직넘버라고 부릅니다.
이 매직넘버는 여러 단점이 있어서 이걸 상수/변수로 변경해주셔야 해요.
1. 이 숫자가 뭘 하는 숫자인지 모릅니다
2. 나중에 변경이 필요할 때 다른곳에 동일한 숫자를 쓰고있으면 추적하기 어렵습니다

Best는 상수로 빼주시는거고, 차선책은 변수라도 만들어주시는겁니다.

Ex) `final long cookieTtlMilisecond = 3600 * 12;`
이러면 이 숫자의 용도를 명확하게 알 수 있겠죠?

2022-10-26 15:31 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +    }
> 컨트롤러 레벨에서 비즈니스 로직을 수행할 때에는
> 
> 1. 메서드로 해당 기능을 분리하거나
> 2. 베스트는 Util / Service로 해당 로직을 분리해야합니다
>    컨트롤러는 비즈니스로직을 처리하기 부적절한 레이어에요. 이런 로직은 재사용하거나 관심사를 모을 수 있게 별도의 클래스로 빼주시는걸 고려해주세요.
> 
> EX) Cookie Utils로 빼거나.. ItemService에 추가하거나

트랜잭션이 필요한 부분은 service로 빼겠습니다.

2022-10-26 17:32 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +        cookie.setMaxAge(3600 * 12);
> 비즈니스 로직에 숫자가 그대로 들어있는걸 매직넘버라고 부릅니다. 이 매직넘버는 여러 단점이 있어서 이걸 상수/변수로 변경해주셔야 해요.
> 
> 1. 이 숫자가 뭘 하는 숫자인지 모릅니다
> 2. 나중에 변경이 필요할 때 다른곳에 동일한 숫자를 쓰고있으면 추적하기 어렵습니다
> 
> Best는 상수로 빼주시는거고, 차선책은 변수라도 만들어주시는겁니다.
> 
> Ex) `final long cookieTtlMilisecond = 3600 * 12;` 이러면 이 숫자의 용도를 명확하게 알 수 있겠죠?

매직넘버 주의하겠습니다!!

2022-10-26 17:32 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +        }
> 중복되는 로직은 메서드로 분리해주세요

옙

2022-10-26 17:45 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +        else {
> else문 쓰지않는것을 목표로 해보세요. else문을 쓰는 순간 코드 가독성이 많이 떨어집니다. 자세한 내용은 요거 참고해주세요 https://stackoverflow.com/questions/9191388/it-is-more-efficient-to-use-if-return-return-or-if-else-return

early return 패턴 이라고 하네요!! 일찍 return시켜주는 방법 !!

2022-10-29 23:23 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +    private static final long COOKIE_MAX_SIZE = 7;
이 상수는 컨트롤러 외부에서 쓸 일이 없을까요?

2022-10-29 23:23 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +            }
이 부분 조건식이 `>=`인게 어색해보입니다.
MAX_SIZE가 10이라면 쿠키는 10개까지 담을 수 있어야겠죠? 그렇지만 `>=`라면 MAX_SIZE와 동일한 크기를 담아도 예외처리 될 것으로 보입니다.

2022-10-29 23:23 UTC, yyy9942 commented
다시 빌드가 안되는걸로 보입니다. 빌드 되도록 만들어주세요~

2022-10-31 08:49 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +    private static final long COOKIE_MAX_SIZE = 7;
> 이 상수는 컨트롤러 외부에서 쓸 일이 없을까요?

현재는 컨트롤러에서만 사용하지만 확장성을 위해 상수클래스로 변경하도록 하겠습니다.

2022-11-01 06:07 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +            }
> 이 부분 조건식이 `>=`인게 어색해보입니다. MAX_SIZE가 10이라면 쿠키는 10개까지 담을 수 있어야겠죠? 그렇지만 `>=`라면 MAX_SIZE와 동일한 크기를 담아도 예외처리 될 것으로 보입니다.

이부분은 executeSetCookie() 를 사용하기 전에 예외처리 하기 때문에 이미 MAX_SIZE 만큼의 상품을 담고 MAX_SIZE + 1 상품을 담았을 경우에만 예외처리 됩니다. ㅠㅠ

2022-11-01 06:14 UTC, suyeonkwong commented
> 다시 빌드가 안되는걸로 보입니다. 빌드 되도록 만들어주세요~

커밋 안된 클래스가 있었습니다. 주의하겠습니다.!

2022-11-03 12:50 UTC, yyy9942 requested changes

2022-11-04 11:02 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +    public void setCart(HttpServletRequest request, HttpServletResponse response) {
> 지금 발견한 부분인데 메서드명이 명시적이지 않아보입니다. setCart라는건 단순히 cart에 대한 setter를 한다는 뜻인데요 이 컨트롤러의 메서드는 그런역할만 수행하고있지는 않겠죠? 어떤 이름으로 지어야할지 애매하다면 이 컨트롤러의 행위에 집중해서 이름을 지어보세요.
> 
> 장바구니에 상품 담기 - 라는 행위가 명시적으로 드러나면 좋겠습니다. 다른 컨트롤러 메서드들도 수정해주세요

addItemToCart 처럼 명시적으로 다 변경하겠습니다.

2022-11-04 11:02 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +    public ResponseEntity<List<CartResponse>> getCartMember(HttpServletRequest request, @AuthenticationPrincipal PrincipalDetails principalDetails) {
> 이런부분도 단순히 getCartMember라는 메서드명만으로는 이 메서드가 어떤 행위를하는지 유추하기 어렵습니다. 내부 동작을 까봐야 무엇을 하는 메서드인지 알 수 있을거에요. 협업의 관점, 유지보수의 관점으로 보았을 때 메서드명을 잘 지어주는것도 중요합니다 :)

네 ㅠㅠ

2022-11-12 10:59 UTC, yyy9942 approved these changes
고생하셨습니다~ 머지하셔도 좋습니다.

2022-11-12 18:56 UTC, merged