Feature/payment
E-TF/Fresh-place pull request #9
Opened 2022-11-03 10:20 UTC by suyeonkwong

외부 api (카카오페이)를 사용해서 결제 기능을 구현했습니다. 

결제 과정은 다음과 같습니다.
![payment](https://user-images.githubusercontent.com/80368511/199693211-976ec542-910f-49fd-8256-9b6a9eb47001.png)

결제 준비를 위해 서버에서 api에 요청해야 하는 정보는 다음과 같습니다. 
![request](https://user-images.githubusercontent.com/80368511/199693669-7ffbc34f-55cf-4c75-ac6c-574ca9fd572c.PNG)

현재 cid 가맹점 코드는 테스트 코드 값을 넣었습니다.
![response](https://user-images.githubusercontent.com/80368511/199694582-52420d34-cf51-41b0-8e3d-7e79aa312366.PNG)
pc url을 api로 요청할 경우 QR화면이 보여집니다. 

![KakaoTalk_20221103_181955126](https://user-images.githubusercontent.com/80368511/199695390-44a8142d-28cc-437c-9b47-4c2952c2a357.jpg)
핸드폰으로 테스트 결제 화면을 볼 수 있습니다. 

현재는 단건 주문 테스트이지만 (api와 결제가 완전히 이루어지지 않는 준비 단계임) 다음은 장바구니 데이터와 실제 pg token값을 받아와 테스트가 아닌 실제 결제 성공 페이지까지 완료하는 작업을 하겠습니다.

2022-11-03 11:14 UTC, suyeonkwong commented
pr제목은 변경이 불가능할까요..?

2022-11-03 12:43 UTC, yyy9942 commented
@suyeonkwong 
![image](https://user-images.githubusercontent.com/46917538/199723327-641cb10b-e9bf-4731-a398-5da2b1aaf42a.png)
이거 누르시면 됩니다

2022-11-03 13:53 UTC, TaeWonn commented
![스크린샷 2022-11-03 오후 10 51 38](https://user-images.githubusercontent.com/50649798/199738775-d8044d95-2e11-410d-9b9a-137f77835e65.png)

위 4개 커밋은 하나로 합쳐도 될 내용인거 같아요!
이미 push된 코드는 어쩔 수 없지만 이후부터 합쳐서 올리면 리뷰하는데 도움이 될거 같아요!

2022-11-04 08:32 UTC, yyy9942 requested changes

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/RestTemplateConfig.java
> +        restTemplate.setRequestFactory(new HttpComponentsClientHttpRequestFactory());
`HttpComponentsClientHttpRequestFactory`에 별도 설정을 추가하지 않았는데 왜 `HttpComponentsClientHttpRequestFactory`를 사용하셨나요?

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/AccountController.java
> +        fSignupService.signupFacade(signupRequest);
이미 facade service를 호출하고있는데 메서드명까지 `signupFacade`일 필요는 없어보입니다. 이름 변경을 하신 이유가 있나요?

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +    }
지금 회원과 비회원의 장바구니 호출 URL이 다른거같은데 꼭 그래야할 필요가 있을까요?
클라이언트입장에서는 불필요한 분기문으로 보입니다.

동일한 `/public/cart`로 호출하되 서버 내부에서 로그인했는지/안했는지 여부를 따라 분기처리를 해주면 될것으로 보입니다. 그렇지 않으면 회원이 `/public/cart`로 호출하거나 비회원이 `/members/cart`로 호출하는걸 막아야합니다(비회원이 호출하는건 권한단에서 막히겠지만요)

회원/비회원 모두 호출할 수 있다는 의미인 `/public/cart`로 엔드포인트를 지정해주는게 더 간결하지 않을까요?

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +    }
REST한 API에서는 URL과 Method만으로 행위를 유추할 수 있어야합니다.
`/public/cart`에 POST 요청이라면 장바구니에 아이템을 추가하는게 아니라 장바구니 자체를 추가하는것으로 보일거에요.

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +            Cookie[] cookies = CookieUtils.executeRemoveCookies(request.getCookies(), Cookies.COOKIE_PATH_FOR_PUBLIC);
메서드에 execute는 빠지는게 자연스러워보입니다. removeCookies 또는 removeItem 등으로 해주세요.

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/cart/CartResponse.java
> +}
장바구니의 response값인데 내용은 item response로 보입니다. 장바구니 response DTO가 맞나요?

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/kakaopay/KakaoPayReadResponse.java
> +    private LocalDateTime created_at;
자바 코드의 컨밴션은 camel case입니다. snake case를 사용하는건 지양해주세요.
물론 response의 컬럼이 snake case겠지만 그러면 해당 snake case를 받아와 camel case 컬럼으로 매핑해주면 될것같네요.

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/order/OrderItem.java
> +}
생성된 이후 변경될 여지가 없는 컬럼이라면 final 처리로 불변성을 보장해주는것도 고려해주세요

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/FCartReadService.java
> +    }
추가적으로 매직넘버가 계속 보이고있습니다. 매직넘버를 사용하지 않도록 주의해주세요

2022-11-04 08:32 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/payment/KAKAOPay.java
> +        return (long) Math.random() * 10000000000L + 1;
매직넘버 사용 자제해주세요~

2022-11-04 08:32 UTC, yyy9942 commented
추가적으로 최근 테스트코드가 올라오고있지 않습니다.
테스트코드도 잊지말고 작성해주세요.

2022-11-04 10:27 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/AccountController.java
> +        fSignupService.signupFacade(signupRequest);
> 이미 facade service를 호출하고있는데 메서드명까지 `signupFacade`일 필요는 없어보입니다. 이름 변경을 하신 이유가 있나요?

signupIneer클래스를 감싸고 있는 메서드라 signupFacade라고 변경했습니다. 이부분은 다시 보니까 굳이 라는 생각이 드네요,, 변경하도록 하겠습니다.

2022-11-04 10:30 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +    }
> REST한 API에서는 URL과 Method만으로 행위를 유추할 수 있어야합니다. `/public/cart`에 POST 요청이라면 장바구니에 아이템을 추가하는게 아니라 장바구니 자체를 추가하는것으로 보일거에요.

장바구니 자체를 추가 하는것처럼 보일 수도 있을것같습니다! url과 메서드 네임을 행위를 유추할 수 있도록 변경하겠습니다.

2022-11-04 10:38 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +            Cookie[] cookies = CookieUtils.executeRemoveCookies(request.getCookies(), Cookies.COOKIE_PATH_FOR_PUBLIC);
> 메서드에 execute는 빠지는게 자연스러워보입니다. removeCookies 또는 removeItem 등으로 해주세요.

네~

2022-11-04 10:39 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/cart/CartResponse.java
> +}
> 장바구니의 response값인데 내용은 item response로 보입니다. 장바구니 response DTO가 맞나요?

네 장바구니를 get요청 했을 때 보이는 장바구니에 담긴 아이템 정보들 입니다. 순서대로 상품명, 상품 수, 원가, 할인가 순 입니다.

2022-11-04 10:50 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/FCartReadService.java
> +    public List<CartResponse> executeReadCookiesNonMember(final Cookie[] cookies) {
> execute라는 네이밍이 지속적으로 보이는데요, execute라는 prefix가 꼭 필요할까요?

아니요 불필요합니다. 변경하겠습니다!

2022-11-04 10:53 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/S3Utils.java
> +//        objectMetadata.setCacheControl("max-age=3600");
> 주석처리보단 코드 삭제를 하는것이 좋습니다. 삭제처리를 해도 git log에 남기때문에 언제든 복구할 수 있고 주석처리된 코드는 코드를 깔끔하지 못하게 관리되는것처럼 만들거든요

주석 처리 ㅠㅠ 주의 하도록 하겠습니다.

2022-11-04 10:54 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/payment/KAKAOPay.java
> +public class KAKAOPay {
> 인텔리제이 자체에서 글자 맞춤법이 깨지면 밑줄 표시 되는 부분이 거슬려서 전체를 대문자로 바꿨는데 제가 클래스명 규칙을 잘 적용하지 못했네요.. 부끄럽습니다.

2022-11-04 11:07 UTC, suyeonkwong commented
> ![스크린샷 2022-11-03 오후 10 51 38](https://user-images.githubusercontent.com/50649798/199738775-d8044d95-2e11-410d-9b9a-137f77835e65.png)
> 
> 위 4개 커밋은 하나로 합쳐도 될 내용인거 같아요! 이미 push된 코드는 어쩔 수 없지만 이후부터 합쳐서 올리면 리뷰하는데 도움이 될거 같아요!

네 비슷한 내용의 커밋을 묶을 수 있다는것을 처음 알았습니다! 알려주셔서 감사합니다.

2022-11-04 11:52 UTC, yyy9942 commented on src/main/java/individual/freshplace/dto/cart/CartResponse.java
> +}
장바구니에 여러 상품이 담겨있을텐데 해당 response dto에는 하나의 상품정보만 보여주는거같아요. 
논리적으로 하나의 장바구니 DTO 안에 아이템 DTO가 리스트로 있어야하지 않을까요?

2022-11-04 12:24 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/cart/CartResponse.java
> +}
> 장바구니에 여러 상품이 담겨있을텐데 해당 response dto에는 하나의 상품정보만 보여주는거같아요. 논리적으로 하나의 장바구니 DTO 안에 아이템 DTO가 리스트로 있어야하지 않을까요?

하나의 장바구니 DTO안에 아이템 DTO가 리스트 형식으로 있어야 한다면 장바구니 자체에 대한 부가적인 정보가 필요한데 (예를 들면 장바구니 번호) 현재  장바구니 테이블을 사용하지 않고 있고 만약 하나의 논리적인 장바구니 DTO가 필요하다면 장바구니의 유효시간 정도의 정보가 필요한데 사용자에게 보통 장바구니 유효시간을 보여주지 않는다고 생각했습니다.  그래서 장바구니 아이템 리스트를 하나의 장바구니 DTO에 넣는것과 아이템 리스트를 보여주는 결과가 똑같다고 생각했습니다. 
[
    {
        "itemName": "냉동 국산 유기능 블루베리",
        "itemCounting": 2,
        "price": 40000,
        "discountPrice": 37200
    },
    {
        "itemName": "생 우유 모나카",
        "itemCounting": 2,
        "price": 18800,
        "discountPrice": 17484
    }
]

코드를 볼때 명시적으로 정확히 하나의 구분된 장바구니 DTO가 생성된것처럼 보이는게 좋다는 말씀이시면 저도 동의 합니다! 이 부분은 고치도록 하겠습니다.

2022-11-04 12:26 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/kakaopay/KakaoPayReadResponse.java
> +    private LocalDateTime created_at;
> 자바 코드의 컨밴션은 camel case입니다. snake case를 사용하는건 지양해주세요. 물론 response의 컬럼이 snake case겠지만 그러면 해당 snake case를 받아와 camel case 컬럼으로 매핑해주면 될것같네요.

ObjectMapper를 사용해서 변경하는 방법이 있는것같습니다! 고치도록 하겠습니다.

2022-11-04 12:28 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/order/OrderItem.java
> +}
> 생성된 이후 변경될 여지가 없는 컬럼이라면 final 처리로 불변성을 보장해주는것도 고려해주세요

오늘 피드백 받기 전에 고쳐놨는데.. ㅠㅠ 신중하게 작성하겠습니다.

2022-11-04 12:37 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/RestTemplateConfig.java
> +        restTemplate.setRequestFactory(new HttpComponentsClientHttpRequestFactory());
> `HttpComponentsClientHttpRequestFactory`에 별도 설정을 추가하지 않았는데 왜 `HttpComponentsClientHttpRequestFactory`를 사용하셨나요?

이부분은 HttpClient builder를 사용했는데 저는 구현체가 하나인줄 알았는데 갑자기 처음보는 CloseableHttpClient가 defualt로 변경된듯하여 CloseableHttpClient와 DefaultHttpClient 차이점을 찾아봐야했는데 시간적 여유가 없어서 아직 제대로 정리 하지 못했습니다. 다시 적용해보겠습니다!

2022-11-04 12:40 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +    }
> 지금 회원과 비회원의 장바구니 호출 URL이 다른거같은데 꼭 그래야할 필요가 있을까요? 클라이언트입장에서는 불필요한 분기문으로 보입니다.
> 
> 동일한 `/public/cart`로 호출하되 서버 내부에서 로그인했는지/안했는지 여부를 따라 분기처리를 해주면 될것으로 보입니다. 그렇지 않으면 회원이 `/public/cart`로 호출하거나 비회원이 `/members/cart`로 호출하는걸 막아야합니다(비회원이 호출하는건 권한단에서 막히겠지만요)
> 
> 회원/비회원 모두 호출할 수 있다는 의미인 `/public/cart`로 엔드포인트를 지정해주는게 더 간결하지 않을까요?

서버 내부에서 처리해보도록 하겠습니다.

2022-11-04 12:42 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/FCartReadService.java
> +    }
> 추가적으로 매직넘버가 계속 보이고있습니다. 매직넘버를 사용하지 않도록 주의해주세요

네..

2022-11-04 12:42 UTC, suyeonkwong commented
> 추가적으로 최근 테스트코드가 올라오고있지 않습니다. 테스트코드도 잊지말고 작성해주세요.

네..

2022-11-04 12:44 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/payment/KAKAOPay.java
> +    public String addKAKAOPayReadyResponse(String memberId, OrderItem orderItem) throws URISyntaxException {
> throws URISyntaxException 이 있는데요 이 부분에 대해 복구가 가능한것이 아니라면 RuntimeException 하위 Exception으로 포장해주는것이 좋을거같네요.

예외를 던지지 않고 포장하도록 하겠습니다.

2022-11-04 12:49 UTC, suyeonkwong commented
> 코드 리뷰가 너무 커서 보기힘듭니다! 쪼개서 올려주실수 있나요?

혹시 pr 바디 부분을 말씀해주신건가요?? 코드 리뷰 자체가 보기 힘들다는 말이 본문 내용을 말씀해주신거죠?????

2022-11-10 16:57 UTC, suyeonkwong commented
feature/cart 의 리뷰에 대한 변경사항이 feature/payment에 commit되었습니다. 혼란을 드려 죄송합니다.

2022-11-12 15:43 UTC, yyy9942 requested changes
테스트코드 작성 시도가 점점 좋아지고있습니다. 지속적으로 신경써주세요.

2022-11-12 15:43 UTC, yyy9942 commented on src/main/java/individual/freshplace/service/FCartReadService.java
>      }
기존 로직에서 이런식으로 변경한다면 시간복잡도는 어떻게될까요?

2022-11-12 15:43 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/S3Utils.java
>      private final AmazonS3Client amazonS3Client;
유틸은 상태를 가지지 않습니다.
`amazonS3Client`이라는 상태를 가지면 서비스레이어로 봐야할거같은데 Util로 변경한 이유가 있나요?

2022-11-12 15:43 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/payment/KakaoPay.java
> +    public PayView getKAKAOPayReadyResponse(final String memberId, final List<OrderItem> orderItems) {
이부분 이전 PR이랑 충돌날거같은데 잘 해결해보시지요.
KAKAO -> Kakao로 변경도 해주시고요

2022-11-12 15:43 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/payment/KakaoPay.java
> +    private MultiValueMap<String, String> setParamsApprove(String pg_token, PayView payView) {
pg_token 이부분도 카멜케이스 지켜주세요

2022-11-14 15:04 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/payment/KakaoPay.java
> +    private MultiValueMap<String, String> setParamsApprove(String pg_token, PayView payView) {
> pg_token 이부분도 카멜케이스 지켜주세요

넵

2022-11-14 15:07 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/payment/KakaoPay.java
> +    public PayView getKAKAOPayReadyResponse(final String memberId, final List<OrderItem> orderItems) {
> 이부분 이전 PR이랑 충돌날거같은데 잘 해결해보시지요. KAKAO -> Kakao로 변경도 해주시고요

넵

2022-11-14 15:08 UTC, suyeonkwong commented on src/main/java/individual/freshplace/dto/cart/CartOnItem.java
> +public class CartOnItem {
> CartOnItem이라는 명명이 어색해보입니다. CartItem이 어떨까요?

넵

2022-11-14 15:47 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/FCartReadService.java
> +                        Math.round(item.getPrice() * cookiesMap.get(item.getItemSeq()) * (PERCENTAGE_INTEGER - Membership.findByCodeName(profile.getMembership()).getDiscountRate()) / PERCENTAGE_SHORT
> `Math.round(item.getPrice() * cookiesMap.get(item.getItemSeq()) * (PERCENTAGE_INTEGER - Membership.findByCodeName(profile.getMembership()).getDiscountRate()) / PERCENTAGE_SHORT)` 이부분은 계산식이 들어간듯한데요, 이런 계산식은 별도 서비스로 관리하거나 별도 메서드로 빼주셔야 관리하기 좋습니다. 예를 들어, 나중에 할인율이 23%가나왔는데 이걸 추적한다면 찾기 쉽도록 말이에요

넵 메서드로 빼주겠습니다.

2022-11-14 16:03 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/FCartReadService.java
>      }
> 기존 로직에서 이런식으로 변경한다면 시간복잡도는 어떻게될까요?

3제곱에서 1로 변경됩니다!

2022-11-16 13:42 UTC, yyy9942 requested changes

2022-11-16 13:42 UTC, yyy9942 commented on src/main/java/individual/freshplace/config/JasyptConfig.java
> +    }
이건 어떤용도로 사용하신건가요?

2022-11-16 13:42 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/payment/KakaoPay.java
> +        return kakaoPayApprovalResponse;
변수는 선언시 꼭 초기화해주세요. 초기화를 하지 않고 다른곳에서 초기화할 경우 NPE발생의 가능성이 높아지고, 어느곳에서 데이터가 들어가는지 추적하기 어려워집니다.

또한 try-catch 내부에서만 사용한다면 해당 블록 내부에 선언해서 변수를 외부로 노출하지 말아주세요.
```suggestion
        

        try {
         KakaoPayApprovalResponse   kakaoPayApprovalResponse = restTemplate.postForObject(new URI(paymentApproveRequestUrl), body, KakaoPayApprovalResponse.class);
         return kakaoPayApprovalResponse;
        } catch (URISyntaxException e) {
            throw new UriException(ErrorCode.NON_FOUND, paymentApproveRequestUrl);
        }

        
```

2022-11-16 14:21 UTC, suyeonkwong commented on src/main/java/individual/freshplace/config/JasyptConfig.java
> +    }
> 이건 어떤용도로 사용하신건가요?

배포할때 gitignore 설정때문에 db정보같은 것들이 문제가 있어서 인코딩설정하고 올려주려고 했습니다.

2022-11-16 14:22 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/payment/KakaoPay.java
> +        return kakaoPayApprovalResponse;
> 

try catch 내부에서 return 하도록 하겠습니다.

2022-11-16 14:29 UTC, suyeonkwong commented on src/main/java/individual/freshplace/service/FCartReadService.java
>      }
> 1은 아니에요~ List를 한번 순회하기때문에 최소 N 이상입니다.

아 3제곱에서 1제곱으로 바뀐다는 의미였습니다. n3 -> n ㅎㅎㅎ

2022-11-16 14:29 UTC, suyeonkwong commented on src/main/java/individual/freshplace/controller/CartController.java
> +            PrincipalDetails principalDetails = (PrincipalDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
> 앞으로도 SecurityContextHolder를 통해 `PrincipalDetails`을 꺼내올일이 많을거같은데 이 역할을 할 유틸리티를 만드는건 어떨까요? 매번 타입캐스팅과 메서드 체이닝을 안해도 될거같습니다.

Util로 변경하니까 편합니다 ㅎㅎ

2022-11-17 14:02 UTC, yyy9942 commented on src/main/java/individual/freshplace/controller/CartController.java
> +            PrincipalDetails principalDetails = (PrincipalDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
아직 이부분은 변경이 안된거같은데 확인부탁드려요

2022-11-17 14:03 UTC, yyy9942 commented on src/main/java/individual/freshplace/util/PrincipalUtils.java
> +    }
만약에 로그인 되지 않은 상태에서 이 유틸에서 유저정보를 조회하려고한다면 어떻게 될까요?

2022-11-18 12:26 UTC, suyeonkwong commented on src/main/java/individual/freshplace/util/PrincipalUtils.java
> +    }
> 만약에 로그인 되지 않은 상태에서 이 유틸에서 유저정보를 조회하려고한다면 어떻게 될까요?

exception이 발생할것같습니다. 예외처리를 해야할것같습니다.

2022-11-18 12:27 UTC, suyeonkwong commented on src/main/resources/application-db.yml
> +    password: ENC(pC2eHGbDZRWOiVv1DkdLY7OnSo4FzPUG)
> 이건 어떤 암호화를 사용하신건가요?

'PBEWithMD5AndDES' 암호화 방법입니다!.

2022-11-19 07:07 UTC, yyy9942 approved these changes
고생하셨습니다

2022-11-19 07:10 UTC, merged